import {StyleSheet} from 'react-native';
import {colors, layout, radii, spacing, typography} from '../../../theme';

export const styles = StyleSheet.create({
  // ─── Layout ──────────────────────────────────────────────────────────────
  container: {flex: 1, backgroundColor: colors.background},
  scrollViewport: {flex: 1},
  scroll: {
    paddingHorizontal: layout.screenPadding,
    paddingTop: layout.screenPadding,
    paddingBottom: layout.bottomInset,
    gap: layout.screenGap,
  },
  loadingContainer: {flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.sm},
  loadingText: {color: colors.textMuted, fontSize: typography.body},
  refreshSpinnerWrap: {
    position: 'absolute',
    top: 8,
    left: 0,
    right: 0,
    zIndex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshSpinnerWrapActive: {
    opacity: 1,
    transform: [{translateY: 8}],
  },
  refreshSpinner: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshSpinnerActive: {
    transform: [{scale: 1}],
  },

  // ─── Page Header (device linked — not a card) ────────────────────────────
  pageHeader: {
    paddingTop: 0,
    paddingBottom: 0,
    gap: spacing.sm,
  },
  pageOverline: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  pageHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: spacing.sm,
  },
  pageHeaderLeft: {gap: spacing.xxs},
  pageHeaderRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  deviceNameButton: {
    alignSelf: 'flex-start',
  },
  pageStatusText: {
    color: colors.text,
    fontSize: typography.pageTitle,
    fontWeight: '800',
    letterSpacing: -1.2,
    lineHeight: 38,
  },
  pageHeaderMeta: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  headerActionButton: {
    width: layout.iconButton,
    height: layout.iconButton,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ─── Status Pill ─────────────────────────────────────────────────────────
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    minHeight: 36,
  },
  statusPillOn: {backgroundColor: colors.successSurface, borderColor: colors.successBorder},
  statusPillOff: {backgroundColor: colors.surface, borderColor: colors.border},
  statusDot: {width: 8, height: 8, borderRadius: 4},
  statusDotOn: {backgroundColor: colors.successText},
  statusDotOff: {backgroundColor: colors.textMuted},
  statusPillText: {color: colors.text, fontSize: 13, fontWeight: '700'},

  // ─── Device Switcher (inside page header) ────────────────────────────────
  deviceSwitcherRow: {gap: spacing.xs, paddingTop: spacing.sm},
  deviceSwitcherHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  switcherLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  switcherMeta: {
    color: colors.textTertiary,
    fontSize: 12,
    fontWeight: '600',
  },
  deviceCycleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  deviceCycleButton: {
    width: layout.chromeSize,
    height: layout.chromeSize,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deviceCycleCurrent: {
    flex: 1,
    minHeight: 40,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  deviceCycleCurrentText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '600',
  },
  devicePillWrap: {flexDirection: 'row', gap: spacing.xs, flexWrap: 'wrap'},
  devicePill: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    minHeight: 36,
    justifyContent: 'center',
  },
  devicePillActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  devicePillText: {color: colors.text, fontSize: 13, fontWeight: '600'},
  devicePillTextActive: {color: colors.accent},

  // ─── Quiet Hours Section ────────────────────────────────────────────────────
  quietSection: {
    backgroundColor: colors.surface,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: layout.cardPaddingLg,
    gap: layout.screenGap,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: colors.border,
  },

  // ─── Generic Card ─────────────────────────────────────────────────────────
  card: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: layout.cardPaddingLg,
    gap: layout.screenGap,
  },
  noDeviceCard: {borderColor: colors.warning, borderStyle: 'dashed'},
  offlineCard: {borderColor: colors.accent},
  offlineHeaderRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.md},
  offlineHeaderCopy: {flex: 1, gap: spacing.xxs},
  addDisplayCard: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: layout.cardPaddingLg,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  addDisplayCardCopy: {
    flex: 1,
    gap: spacing.xxs,
  },
  addDisplayTitle: {
    color: colors.text,
    fontSize: typography.bodyLg,
    fontWeight: '800',
  },
  addDisplayBody: {
    color: colors.textMuted,
    fontSize: typography.body,
    lineHeight: 20,
  },
  addDisplayAction: {
    width: layout.chromeSize,
    height: layout.chromeSize,
    borderRadius: layout.chromeSize / 2,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ─── No-Device Card Elements ──────────────────────────────────────────────
  deviceHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  deviceHeaderText: {flex: 1, gap: spacing.xxs},
  sectionLabel: {color: colors.text, fontSize: 15, fontWeight: '800'},
  deviceSubMeta: {color: colors.textMuted, fontSize: 13},

  // ─── Borderless Section ───────────────────────────────────────────────────
  sectionBlock: {gap: spacing.md},
  sectionBlockLabel: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '600',
  },
  heroBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  mtaBadge: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    paddingHorizontal: 6,
  },
  mtaBadgeText: {fontSize: 10, fontWeight: '900'},
  heroHeader: {gap: spacing.xxs},
  heroBrandLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  heroDisplayMeta: {color: colors.textMuted, fontSize: 12, lineHeight: 17},

  // ─── Hero Label Row (section label + inline carousel) ────────────────────
  heroNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  carouselControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    flexShrink: 0,
  },
  slideshowControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.sm,
    marginTop: spacing.xs,
  },
  carouselArrowBtn: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dotRow: {
    flexDirection: 'row',
    gap: spacing.xxs,
    alignItems: 'center',
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.border,
  },
  dotActive: {
    width: 14,
    height: 5,
    borderRadius: 3,
    backgroundColor: colors.accent,
  },

  // ─── LED Display ─────────────────────────────────────────────────────────
  ledContainer: {width: '100%', marginTop: spacing.xs},

  // ─── Empty / Error State ──────────────────────────────────────────────────
  emptyState: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: layout.cardPaddingLg,
    gap: spacing.md,
  },
  emptyStateBody: {gap: spacing.xs},
  emptyStateTitle: {color: colors.text, fontSize: 15, fontWeight: '800'},
  emptyStateText: {color: colors.textMuted, fontSize: 13, lineHeight: 19},
  commandError: {color: colors.warning, fontSize: 12},
  setupButton: {
    backgroundColor: colors.accent,
    minHeight: layout.buttonHeight,
    borderRadius: radii.md,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.md,
  },
  setupButtonText: {color: colors.onAccent, fontWeight: '800', fontSize: 13},

  // ─── Card Section Header ──────────────────────────────────────────────────
  cardHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  cardTitle: {color: colors.text, fontSize: 16, fontWeight: '700'},
  cardSubtitle: {color: colors.textMuted, fontSize: 13, marginTop: spacing.xxs},

  // ─── Quiet Hours Header ───────────────────────────────────────────────────
  quietHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  quietHeaderCopy: {flex: 1, gap: spacing.xxs},
  quietHeaderControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    flexShrink: 0,
  },
  quietHeaderSwitch: {
    flexShrink: 0,
  },
  quietExpandBtn: {
    width: 32,
    height: 32,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
  },
  quietDescription: {
    flex: 1,
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  quietDescriptionDisabled: {opacity: 0.6},

  // ─── Quiet Hours / Time Fields ────────────────────────────────────────────
  quietMetaText: {color: colors.textTertiary, fontSize: 12, lineHeight: 17},
  quietRangeRow: {flexDirection: 'row', gap: spacing.sm},
  timeField: {
    flex: 1,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: 6,
  },
  timeFieldLabel: {
    color: colors.textTertiary,
    fontSize: 11,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 1.0,
  },
  timeFieldControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  timeFieldButton: {
    width: layout.chromeSize,
    height: layout.chromeSize,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeFieldButtonText: {color: colors.text, fontSize: 18, fontWeight: '600'},
  timeFieldValue: {color: colors.text, fontSize: 18, fontWeight: '700', letterSpacing: -0.3},
  timeFieldDisabled: {opacity: 0.45},
  timePickerButton: {
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xxs,
    justifyContent: 'center',
    gap: spacing.xxs,
  },
  timePickerValue: {color: colors.text, fontSize: 15, fontWeight: '800'},
  timePickerModalBackdrop: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'flex-end',
  },
  timePickerModalSheet: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: radii.lg,
    borderTopRightRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xl,
    gap: spacing.sm,
  },
  timePickerModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timePickerModalAction: {
    minWidth: 56,
    minHeight: 36,
    justifyContent: 'center',
  },
  timePickerModalActionText: {color: colors.textMuted, fontSize: 14, fontWeight: '700'},
  timePickerModalActionTextPrimary: {color: colors.accent},
  timePickerModalTitle: {color: colors.text, fontSize: 15, fontWeight: '800'},
  timePickerModalControl: {alignSelf: 'center'},

  // ─── Secondary Button ─────────────────────────────────────────────────────
  secondaryButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  secondaryButtonText: {color: colors.text, fontSize: 13, fontWeight: '700'},
});
