import {StyleSheet} from 'react-native';
import {colors, radii, spacing} from '../../../theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
  loadingText: { color: colors.textMuted, fontSize: 13 },
  scroll: { padding: spacing.lg, paddingBottom: 120, gap: spacing.md },
  header: { gap: 4, alignItems: 'center' },
  title: {
    color: colors.text,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  subtitle: {
    color: colors.textMuted,
    fontSize: 13,
    textAlign: 'center',
    maxWidth: 300,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm,
  },
  sectionLabel: { color: colors.text, fontSize: 13, fontWeight: '800' },
  deviceHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: spacing.sm,
  },
  deviceHeaderText: { flex: 1 },
  deviceName: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 2,
  },
  deviceSubMeta: { color: colors.textMuted, fontSize: 11, marginTop: 3 },
  onlineChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    borderRadius: radii.md,
    borderWidth: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  onlineChipOn: { backgroundColor: '#0E2B21', borderColor: '#1B5E4A' },
  onlineChipOff: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
  },
  onlineDot: { width: 8, height: 8, borderRadius: 4 },
  onlineDotOn: { backgroundColor: '#34D399' },
  onlineDotOff: { backgroundColor: colors.textMuted },
  onlineChipText: { color: colors.text, fontSize: 12, fontWeight: '800' },
  deviceSwitcherRow: { gap: spacing.xs },
  switcherLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  devicePill: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  devicePillActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  devicePillText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  devicePillTextActive: { color: colors.accent },
  heroCard: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.sm,
  },
  heroTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  heroTitleWrap: { flex: 1 },
  heroBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 4,
  },
  mtaBadge: {
    width: 34,
    minWidth: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    paddingHorizontal: 8,
  },
  mtaBadgeText: { fontSize: 10, fontWeight: '900' },
  heroBrandText: { color: colors.text, fontSize: 12, fontWeight: '800' },
  heroLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  heroTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 2,
  },
  heroMeta: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
  heroArrowRow: { flexDirection: 'row', gap: spacing.xs },
  heroArrowButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroArrowText: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '700',
    marginTop: -2,
  },
  heroFooter: { gap: spacing.xs },
  heroHint: { color: colors.textMuted, fontSize: 11 },
  heroDots: { flexDirection: 'row', gap: 6, alignSelf: 'center' },
  heroDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.border,
  },
  heroDotActive: { backgroundColor: colors.accent },
  emptyHeroState: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
  },
  emptyHeroText: { color: colors.textMuted, fontSize: 12 },
  actionsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs },
  secondaryButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryButtonText: { color: colors.text, fontSize: 12, fontWeight: '700' },
  ghostButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'transparent',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  ghostButtonText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  noDeviceCard: { borderColor: colors.warning, borderStyle: 'dashed' },
  setupButton: {
    backgroundColor: colors.accent,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    alignItems: 'center',
  },
  setupButtonText: { color: colors.background, fontWeight: '800', fontSize: 13 },
  scanAgainText: { color: colors.accent, fontSize: 12, fontWeight: '700', textAlign: 'center' },
  noDeviceText: {
    color: colors.warning,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  commandTs: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '600',
    marginBottom: 4,
  },
  commandJson: {
    color: colors.textMuted,
    fontSize: 11,
    fontFamily: 'monospace',
  },
  commandError: { color: colors.warning, fontSize: 12 },
  quietHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: spacing.sm,
  },
  quietSubtext: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
  stateChip: {
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  stateChipOff: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
  },
  stateChipText: { color: colors.text, fontSize: 11, fontWeight: '800' },
  quietRangeRow: { flexDirection: 'row', gap: spacing.xs },
  timeField: {
    flex: 1,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.xs,
    gap: 6,
  },
  timeFieldLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '700' },
  timeFieldControls: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  timeFieldButton: {
    width: 28,
    height: 28,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeFieldButtonText: { color: colors.text, fontSize: 16, fontWeight: '800' },
  timeFieldValue: { color: colors.text, fontSize: 13, fontWeight: '800' },
});
