import {StyleSheet} from 'react-native';
import {colors, radii, spacing} from '../../../theme';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  keyboardAvoid: {flex: 1},
  scroll: {padding: spacing.lg, paddingBottom: 140, gap: spacing.md},
  topBarWrap: {gap: spacing.xs},
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  topBarSideLeft: {
    width: 88,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  topBarSideRight: {
    width: 116,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  topBarCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  presetNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    maxWidth: '100%',
  },
  presetNameTitle: {color: colors.text, fontSize: 16, fontWeight: '900', textAlign: 'center', maxWidth: 180},
  presetNameEditButton: {
    paddingHorizontal: 2,
    paddingVertical: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetNameEditEmoji: {fontSize: 14},
  renameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.xs,
  },
  renameInput: {
    flex: 1,
    minHeight: 40,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  renameActionButton: {
    minHeight: 40,
    borderRadius: radii.md,
    backgroundColor: colors.accentMuted,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  renameActionButtonText: {color: colors.text, fontSize: 12, fontWeight: '800'},
  renameCancelButton: {
    minHeight: 40,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  backButtonText: {color: colors.text, fontSize: 13, fontWeight: '800'},
  confirmOverlay: {
    flex: 1,
    backgroundColor: '#00000088',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  confirmSheet: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
  },
  confirmTitle: {color: colors.text, fontSize: 16, fontWeight: '800'},
  confirmBody: {color: colors.textMuted, fontSize: 13, marginTop: spacing.xs},
  confirmActions: {flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.xs, marginTop: spacing.md},
  confirmStayButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  confirmStayText: {color: colors.text, fontSize: 13, fontWeight: '700'},
  confirmLeaveButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#5B1C1C',
    backgroundColor: '#2B1010',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  confirmLeaveText: {color: '#FCA5A5', fontSize: 13, fontWeight: '700'},
  modalOverlay: {flex: 1, backgroundColor: '#00000088', justifyContent: 'flex-start', paddingTop: 72},
  modalSheet: {
    marginHorizontal: spacing.lg,
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalOption: {padding: spacing.md},
  modalOptionActive: {backgroundColor: colors.accentMuted},
  modalOptionText: {color: colors.text, fontSize: 15, fontWeight: '700'},
  modalOptionTextActive: {color: colors.accent},
  previewWrapper: {marginBottom: spacing.xs},
  previewCard: {
    borderRadius: radii.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#0F131A',
    backgroundColor: '#020204',
    padding: spacing.md,
    minHeight: 180,
  },
  previewHeaderRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  previewStation: {color: '#E9F5FF', fontSize: 18, fontWeight: '900', flex: 1, marginRight: spacing.sm},
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radii.md,
  },
  statusGood: {backgroundColor: '#0B3B2E'},
  statusDotLarge: {width: 8, height: 8, borderRadius: 4, backgroundColor: '#5CE1E6'},
  statusPillText: {color: '#fff', fontWeight: '800', fontSize: 11},
  previewList: {marginTop: spacing.sm, gap: spacing.sm},
  previewRowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#1E232B',
    padding: spacing.sm,
    backgroundColor: '#090C12',
  },
  previewRowButtonActive: {borderColor: colors.accent, backgroundColor: '#0E1720'},
  previewSlotBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#38414A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewSlotBadgeText: {color: '#C7CFD6', fontSize: 12, fontWeight: '800'},
  routeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: radii.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  routeBadgeText: {fontWeight: '900', fontSize: 16},
  routeDir: {color: '#E9ECEF', fontSize: 11, fontWeight: '700', opacity: 0.8},
  previewMain: {flex: 1, gap: 2},
  previewStationName: {fontSize: 14, fontWeight: '800'},
  previewArea: {fontSize: 12, opacity: 0.75},
  previewTimes: {fontSize: 12, fontWeight: '700'},
  card: {
    backgroundColor: 'transparent',
    borderRadius: radii.lg,
    borderWidth: 0,
    padding: 0,
    gap: spacing.sm,
  },
  sectionLabel: {color: colors.text, fontSize: 14, fontWeight: '800'},
  layoutRow: {flexDirection: 'row', gap: spacing.xs},
  layoutDropdownLabel: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  layoutDropdownButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  layoutDropdownButtonText: {color: colors.text, fontSize: 12, fontWeight: '700'},
  layoutPillTopRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.accentMuted,
    borderColor: colors.accent,
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    alignSelf: 'flex-end',
  },
  layoutPillTopRightText: {color: colors.accent, fontSize: 13, fontWeight: '700'},
  layoutPillChevron: {color: colors.accent, fontSize: 12, fontWeight: '700'},
  layoutPill: {
    flex: 1,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  layoutPillActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  layoutPillText: {color: colors.text, fontWeight: '700', fontSize: 13},
  layoutPillTextActive: {color: colors.accent},
  layoutHint: {color: colors.textMuted, fontSize: 12},
  editorHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  sectionBlock: {gap: spacing.xs},
  sectionHint: {color: colors.textMuted, fontSize: 12},
  schedule24x7Card: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
    gap: 4,
  },
  schedule24x7Title: {color: colors.text, fontSize: 13, fontWeight: '800'},
  schedule24x7Body: {color: colors.textMuted, fontSize: 12},
  scheduleToggleRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  scheduleToggleLabel: {color: colors.text, fontSize: 13, fontWeight: '800'},
  scheduleToggle: {
    width: 44,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    padding: 2,
    justifyContent: 'center',
  },
  scheduleToggleOn: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  scheduleToggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.textMuted,
  },
  scheduleToggleThumbOn: {
    backgroundColor: colors.accent,
    transform: [{translateX: 18}],
  },
  collapsibleSection: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  collapsibleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  collapsibleArrowBubble: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collapsibleArrow: {color: colors.textMuted, fontSize: 12, fontWeight: '800'},
  collapsibleBody: {paddingTop: 2, gap: spacing.sm},
  selectorField: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  selectorValueText: {color: colors.text, fontSize: 14, fontWeight: '700'},
  selectorCaptionText: {color: colors.textMuted, fontSize: 12, marginTop: 2},
  selectorChevron: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  segmented: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  segment: {flex: 1, paddingVertical: spacing.sm, alignItems: 'center', justifyContent: 'center', minHeight: 44, paddingHorizontal: 4},
  segmentActive: {backgroundColor: colors.accentMuted},
  segmentDisabled: {opacity: 0.4},
  segmentText: {color: colors.textMuted, fontWeight: '700', fontSize: 11, textAlign: 'center'},
  segmentTextActive: {color: colors.accent},
  choiceList: {gap: spacing.xs},
  choiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  choiceRowActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  choiceRowCopy: {flex: 1, gap: 2},
  choiceRowLabel: {color: colors.text, fontSize: 13, fontWeight: '800'},
  choiceRowLabelActive: {color: colors.text},
  choiceRowHint: {color: colors.textMuted, fontSize: 11, lineHeight: 14},
  choiceRowHintActive: {color: colors.textMuted},
  choiceRowCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  choiceRowCheckActive: {borderColor: colors.accent, backgroundColor: colors.accent},
  choiceRowCheckText: {color: colors.background, fontSize: 11, fontWeight: '900'},
  searchRow: {flexDirection: 'row', alignItems: 'stretch', gap: spacing.xs},
  searchInput: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    color: colors.text,
    marginBottom: spacing.xs,
    minHeight: 40,
  },
  searchInputInline: {flex: 1, marginBottom: 0},
  searchDropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    minWidth: 38,
    minHeight: 40,
  },
  searchDropdownButtonCaret: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  stationListInline: {maxHeight: 220},
  stationRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: spacing.sm},
  stationName: {color: colors.text, fontSize: 14, fontWeight: '800'},
  stationMeta: {color: colors.textMuted, fontSize: 12, marginTop: 2},
  chevron: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  chevronSelected: {color: colors.accent},
  listDivider: {height: 1, backgroundColor: colors.border},
  routeGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  routeTile: {
    width: 70,
    height: 70,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  routeTileActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  routeCircle: {width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center'},
  routeCircleText: {fontWeight: '900', fontSize: 18},
  customInput: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    color: colors.text,
  },
  secondarySectionCard: {
    marginTop: spacing.xs,
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
  },
  stepperRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.md},
  stepperButton: {
    width: 36,
    height: 36,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonText: {color: colors.text, fontSize: 18, fontWeight: '800'},
  stepperButtonDisabled: {opacity: 0.45},
  stepperButtonTextDisabled: {color: colors.textMuted},
  stepperValue: {color: colors.text, fontSize: 20, fontWeight: '900', minWidth: 20, textAlign: 'center'},
  timeRangeRow: {flexDirection: 'row', gap: spacing.xs},
  dayPillRow: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, justifyContent: 'center'},
  dayPill: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    minWidth: 54,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  dayPillActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  dayPillText: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  dayPillTextActive: {color: colors.accent},
  timeStepper: {
    flex: 1,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    padding: spacing.xs,
    gap: 6,
  },
  timeStepperLabel: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  timeStepperControls: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.xs},
  timeAdjustButton: {
    width: 34,
    height: 34,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeAdjustButtonText: {color: colors.text, fontSize: 18, fontWeight: '800'},
  timeValue: {color: colors.text, fontSize: 13, fontWeight: '800'},
  saveBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    padding: spacing.md,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  saveButton: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingVertical: spacing.md,
    alignItems: 'center',
  },
  saveButtonDisabled: {opacity: 0.4},
  saveButtonSuccess: {backgroundColor: colors.success},
  saveButtonText: {color: colors.background, fontWeight: '900', fontSize: 15},
  saveHint: {color: colors.textMuted, fontSize: 12, textAlign: 'center'},
  deviceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginBottom: spacing.xs,
  },
  deviceDot: {width: 7, height: 7, borderRadius: 4, flexShrink: 0},
  deviceDotOnline: {backgroundColor: colors.success},
  deviceDotOffline: {backgroundColor: colors.warning},
  deviceLabel: {color: colors.textMuted, fontSize: 11, fontWeight: '700', flex: 1},
  deviceStatus: {fontSize: 11, fontWeight: '700'},
  deviceStatusOnline: {color: colors.success},
  deviceStatusOffline: {color: colors.warning},
  deviceChip: {
    paddingHorizontal: spacing.xs,
    paddingVertical: 3,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  deviceChipActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  deviceChipText: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  deviceChipTextActive: {color: colors.accent},
  noDeviceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xs,
    marginBottom: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.warning,
    backgroundColor: colors.surface,
  },
  noDeviceText: {color: colors.warning, fontSize: 12, fontWeight: '700'},
  liveDisabledCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.md,
    gap: spacing.xs,
  },
  liveDisabledTitle: {color: colors.text, fontSize: 14, fontWeight: '800'},
  liveDisabledBody: {color: colors.textMuted, fontSize: 12},
  emptyHint: {color: colors.textMuted, fontSize: 12},
  stepSection: {gap: spacing.sm},
  stepContainer: {gap: spacing.sm},
  stepNavRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  stepBackButton: {paddingVertical: 4, paddingRight: spacing.sm},
  stepBackText: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  stepTitle: {color: colors.text, fontSize: 22, fontWeight: '900', marginBottom: 4},
  stepSubtitle: {color: colors.textMuted, fontSize: 13, marginBottom: spacing.sm},
  formatCardList: {gap: spacing.sm, paddingBottom: spacing.md},
  formatCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#242933',
    backgroundColor: '#12161C',
    padding: spacing.md,
    gap: spacing.sm,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  fmtSkel: {paddingVertical: spacing.sm, gap: 7},
  fmtSkelRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm},
  fmtSkelBadge: {
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: '#1C2330', flexShrink: 0,
  },
  fmtSkelBody: {flex: 1, gap: 5},
  fmtSkelPrimaryWrap: {
    flex: 1,
    minHeight: 22,
    borderRadius: 5,
    backgroundColor: '#1C2330',
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  fmtSkelPrimaryText: {color: '#D7DEE6', fontSize: 13, fontWeight: '700'},
  fmtSkelSecondaryWrap: {
    minHeight: 18,
    borderRadius: 5,
    backgroundColor: '#1C2330',
    paddingHorizontal: 8,
    justifyContent: 'center',
    width: '100%',
  },
  fmtSkelSecondaryText: {color: '#A9B3BE', fontSize: 13, fontWeight: '600'},
  fmtSkelEta: {
    minWidth: 30,
    height: 22,
    borderRadius: 5,
    backgroundColor: '#1C2330',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  fmtSkelEtaText: {color: '#D7DEE6', fontSize: 10, fontWeight: '700'},
  fmtSkelChipRow: {
    flexDirection: 'row', gap: 5,
    paddingLeft: 36,
  },
  fmtSkelChip: {
    minWidth: 34, height: 18, borderRadius: 4,
    borderWidth: 1, borderColor: '#1C2330', backgroundColor: 'transparent',
    alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4,
  },
  fmtSkelChipText: {color: '#A9B3BE', fontSize: 9, fontWeight: '700'},
  formatGroup: {gap: spacing.sm},
  formatGroupSpaced: {marginTop: spacing.lg},
  formatGroupHeader: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  formatGroupLine: {flex: 1, height: 1, backgroundColor: colors.border},
  formatGroupLabel: {
    color: colors.textMuted, fontSize: 11, fontWeight: '700',
  },
  formatCardDivider: {height: 1, backgroundColor: '#262C35', marginHorizontal: -spacing.md},
  formatCardInfo: {gap: 4},
  formatCardName: {color: colors.text, fontSize: 14, fontWeight: '800'},
  formatCardDesc: {color: colors.textMuted, fontSize: 12, lineHeight: 17},
  formatCardCheck: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatCardCheckText: {color: '#fff', fontSize: 12, fontWeight: '900'},
  transitionContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.md,
  },
  transitionBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transitionBadgeText: {color: '#fff', fontSize: 28, fontWeight: '900'},
  transitionSpinnerPlaceholder: {width: 80, height: 80},
  transitionMessage: {color: colors.text, fontSize: 16, fontWeight: '700', textAlign: 'center'},
  transitionDots: {flexDirection: 'row', gap: 6},
  transitionDot: {width: 6, height: 6, borderRadius: 3, backgroundColor: colors.textMuted},
  lineGroupList: {gap: spacing.md, paddingBottom: spacing.sm},
  lineGroup: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
  },
  lineGroupTitle: {color: colors.textMuted, fontSize: 12, fontWeight: '700', marginBottom: spacing.sm},
  lineGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  lineGridSkeleton: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  lineGridSkeletonTile: {width: 64, height: 64, borderRadius: radii.md, backgroundColor: colors.surface},
  lineBadgeTile: {
    width: 64,
    height: 64,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  lineBadgeTileActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  lineBadgeCircle: {width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center'},
  lineBadgeBusPill: {width: 54, height: 34, borderRadius: 10, paddingHorizontal: 6},
  lineBadgeCommuterRail: {width: 52, height: 52, paddingHorizontal: 4},
  lineBadgeDiamond: {width: 44, height: 44, borderRadius: 8, transform: [{rotate: '45deg'}]},
  lineBadgeText: {fontWeight: '900', fontSize: 18},
  lineBadgeTextCompact: {fontSize: 13},
  lineBadgeBusText: {fontSize: 15, lineHeight: 18, textAlign: 'center', includeFontPadding: false},
  lineBadgeCommuterRailText: {fontSize: 10, lineHeight: 11, textAlign: 'center', includeFontPadding: false, paddingHorizontal: 2},
  lineBadgeTextDiamond: {transform: [{rotate: '-45deg'}]},
  stepSearchInput: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    color: colors.text,
    fontSize: 14,
  },
  stopListScroll: {maxHeight: 360},
  stopSectionHeader: {color: colors.textMuted, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', paddingVertical: spacing.xs, letterSpacing: 0.5},
  stopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  stopRowSelected: {backgroundColor: colors.accentMuted, borderColor: colors.accent, borderBottomColor: colors.accent},
  stopLineDot: {width: 10, height: 10, borderRadius: 5},
  stopLineDotEmpty: {width: 10, height: 10},
  stopRowInfo: {flex: 1},
  stopCheckmark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopCheckmarkText: {color: colors.background, fontSize: 12, fontWeight: '900'},
  stopContextBar: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm},
  stopContextBadge: {width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center'},
  stopContextBadgeBus: {width: 42, borderRadius: 8, paddingHorizontal: 4},
  stopContextBadgeText: {fontWeight: '900', fontSize: 12},
  stopContextBadgeTextBus: {fontSize: 11, lineHeight: 13, includeFontPadding: false},
  stopContextLabel: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  verifyingBadge: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  doneStepContainer: {gap: spacing.sm},
  contextChipRow: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs},
  contextChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  contextChipBadge: {width: 20, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center'},
  contextChipBadgeBus: {width: 38, borderRadius: 8, paddingHorizontal: 4},
  contextChipBadgeText: {fontWeight: '900', fontSize: 10},
  contextChipBadgeTextBus: {fontSize: 9, lineHeight: 10, includeFontPadding: false},
  contextChipLabel: {color: colors.text, fontSize: 13, fontWeight: '700', maxWidth: 120},
  contextChipX: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  sectionCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  sectionTitle: {color: colors.text, fontSize: 16, fontWeight: '800', marginBottom: spacing.sm},
  payloadMeta: {color: colors.textMuted, fontSize: 11, marginTop: -spacing.xs, marginBottom: spacing.xs},
  payloadError: {color: colors.warning, fontSize: 12, marginBottom: spacing.xs},
  payloadBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    padding: spacing.sm,
  },
  payloadText: {color: colors.text, fontSize: 11, lineHeight: 16},
});
