import {StyleSheet} from 'react-native';
import {colors, radii, spacing} from '../../../theme';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  keyboardAvoid: {flex: 1},
  scroll: {padding: spacing.lg, paddingBottom: 140, gap: spacing.md},
  topBarWrap: {
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    zIndex: 30,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: 10,
    minHeight: 50,
  },
  topBarSideLeft: {
    width: 80,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  topBarSideRight: {
    width: 90,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  layoutStatusText: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  topBarCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  topBarTitle: {color: colors.text, fontSize: 16, fontWeight: '900', textAlign: 'center'},
  presetNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  presetNameTitle: {color: colors.text, fontSize: 15, fontWeight: '800', textAlign: 'center', maxWidth: 160},
  presetNameEditButton: {
    padding: 4,
  },
  presetNameEditEmoji: {fontSize: 12, color: colors.textMuted},
  renameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.xs,
  },
  renameInput: {
    flex: 1,
    minHeight: 40,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  renameActionButton: {
    minHeight: 40,
    borderRadius: radii.md,
    backgroundColor: colors.accentMuted,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  renameActionButtonText: {color: colors.text, fontSize: 12, fontWeight: '800'},
  renameCancelButton: {
    minHeight: 40,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButton: {
    paddingVertical: 4,
    paddingRight: spacing.xs,
  },
  backButtonText: {color: colors.textMuted, fontSize: 14, fontWeight: '600'},
  confirmOverlay: {
    flex: 1,
    backgroundColor: '#00000088',
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  confirmSheet: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
  },
  confirmTitle: {color: colors.text, fontSize: 16, fontWeight: '800'},
  confirmBody: {color: colors.textMuted, fontSize: 13, marginTop: spacing.xs},
  confirmActions: {flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.xs, marginTop: spacing.md},
  confirmStayButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  confirmStayText: {color: colors.text, fontSize: 13, fontWeight: '700'},
  confirmLeaveButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#5B1C1C',
    backgroundColor: '#2B1010',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  confirmLeaveText: {color: '#FCA5A5', fontSize: 13, fontWeight: '700'},
  modalOverlay: {flex: 1, backgroundColor: '#00000088', justifyContent: 'flex-start', paddingHorizontal: spacing.lg, paddingTop: spacing.lg},
  modalBackdrop: {position: 'absolute', top: 0, right: 0, bottom: 0, left: 0},
  modalSheet: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.xs,
  },
  modalTitle: {color: colors.text, fontSize: 15, fontWeight: '800'},
  modalCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseButtonText: {color: colors.textMuted, fontSize: 12, fontWeight: '900'},
  modalOption: {padding: spacing.md},
  modalOptionActive: {backgroundColor: colors.accentMuted},
  modalOptionText: {color: colors.text, fontSize: 15, fontWeight: '700'},
  modalOptionTextActive: {color: colors.accent},
  previewWrapper: {marginBottom: spacing.xs},
  stickyTopShell: {
    marginHorizontal: -spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.xs,
    backgroundColor: colors.background,
    zIndex: 30,
  },
  stickyPreviewShell: {
    paddingBottom: spacing.xs,
    backgroundColor: colors.background,
    zIndex: 20,
  },
  stickyPreviewHeader: {gap: 2, marginBottom: spacing.xs, alignItems: 'center'},
  stickyPreviewEyebrow: {
    color: '#7DD3FC',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  previewCard: {
    borderRadius: radii.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#0F131A',
    backgroundColor: '#020204',
    padding: spacing.md,
    minHeight: 180,
  },
  previewHeaderRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  previewStation: {color: '#E9F5FF', fontSize: 18, fontWeight: '900', flex: 1, marginRight: spacing.sm},
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 4,
    borderRadius: radii.md,
  },
  statusGood: {backgroundColor: '#0B3B2E'},
  statusDotLarge: {width: 8, height: 8, borderRadius: 4, backgroundColor: '#5CE1E6'},
  statusPillText: {color: '#fff', fontWeight: '800', fontSize: 11},
  previewList: {marginTop: spacing.sm, gap: spacing.sm},
  previewRowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#1E232B',
    padding: spacing.sm,
    backgroundColor: '#090C12',
  },
  previewRowButtonActive: {borderColor: colors.accent, backgroundColor: '#0E1720'},
  previewSlotBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#38414A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewSlotBadgeText: {color: '#C7CFD6', fontSize: 12, fontWeight: '800'},
  routeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: radii.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  routeBadgeText: {fontWeight: '900', fontSize: 16},
  routeDir: {color: '#E9ECEF', fontSize: 11, fontWeight: '700', opacity: 0.8},
  previewMain: {flex: 1, gap: 2},
  previewStationName: {fontSize: 14, fontWeight: '800'},
  previewArea: {fontSize: 12, opacity: 0.75},
  previewTimes: {fontSize: 12, fontWeight: '700'},
  card: {
    backgroundColor: 'transparent',
    borderRadius: radii.lg,
    borderWidth: 0,
    padding: 0,
    gap: spacing.sm,
  },
  builderSection: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(11, 16, 24, 0.84)',
    padding: spacing.md,
    gap: spacing.md,
    shadowColor: '#000',
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: {width: 0, height: 10},
    elevation: 6,
  },
  builderHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  builderHeaderCopy: {flex: 1, gap: 6},
  builderEyebrow: {
    color: '#7DD3FC',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  builderTitle: {color: '#F4F8FC', fontSize: 22, fontWeight: '900'},
  builderProgress: {flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'center', alignSelf: 'center', width: '100%'},
  builderProgressItem: {
    flex: 1,
    gap: 6,
    alignItems: 'center',
    position: 'relative',
    borderRadius: radii.md,
    paddingVertical: spacing.xs,
    paddingHorizontal: 4,
  },
  builderProgressItemEditable: {
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  builderProgressItemActive: {},
  builderProgressTopRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'center', width: '100%'},
  builderProgressConnector: {
    position: 'absolute',
    top: 21,
    left: '50%',
    right: '-50%',
    height: 1,
    backgroundColor: 'rgba(255,255,255,0.09)',
  },
  builderProgressConnectorComplete: {backgroundColor: 'rgba(92, 225, 230, 0.45)'},
  builderProgressDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    backgroundColor: '#0B1018',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    elevation: 2,
  },
  builderProgressDotCenter: {
    zIndex: 3,
    elevation: 3,
  },
  builderProgressDotActive: {
    borderColor: '#7DD3FC',
    backgroundColor: '#173041',
  },
  builderProgressDotComplete: {
    borderColor: '#5CE1E6',
    backgroundColor: '#123239',
  },
  builderProgressDotText: {color: '#9FB0C2', fontSize: 12, fontWeight: '900'},
  builderProgressDotTextActive: {color: '#F4F8FC'},
  builderProgressLabel: {color: '#D8E4EF', fontSize: 12, fontWeight: '800', textAlign: 'center'},
  builderProgressLabelActive: {color: '#F4F8FC'},
  builderProgressValue: {color: '#8EA0B4', fontSize: 11, textAlign: 'center'},
  builderStepPanel: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    backgroundColor: 'rgba(5, 10, 16, 0.54)',
    padding: spacing.sm,
  },
  sectionLabel: {color: colors.text, fontSize: 14, fontWeight: '800'},
  layoutRow: {flexDirection: 'row', gap: spacing.xs},
  layoutDropdownLabel: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  layoutDropdownButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  layoutDropdownButtonText: {color: colors.text, fontSize: 12, fontWeight: '700'},
  layoutPillTopRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.accentMuted,
    borderColor: colors.accent,
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    alignSelf: 'flex-end',
  },
  layoutPillTopRightText: {color: colors.text, fontSize: 12, fontWeight: '700'},
  layoutPillChevron: {color: colors.textMuted, fontSize: 10},
  layoutPill: {
    flex: 1,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  layoutPillActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  layoutPillText: {color: colors.text, fontWeight: '700', fontSize: 13},
  layoutPillTextActive: {color: colors.accent},
  layoutHint: {color: colors.textMuted, fontSize: 12},
  editorHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  sectionBlock: {gap: spacing.xs},
  sectionHint: {color: colors.textMuted, fontSize: 12},
  schedule24x7Card: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
    gap: 4,
  },
  schedule24x7Title: {color: colors.text, fontSize: 13, fontWeight: '800'},
  schedule24x7Body: {color: colors.textMuted, fontSize: 12},
  scheduleToggleRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  scheduleToggleLabel: {color: colors.text, fontSize: 13, fontWeight: '800'},
  scheduleToggle: {
    width: 44,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    padding: 2,
    justifyContent: 'center',
  },
  scheduleToggleOn: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  scheduleToggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.textMuted,
  },
  scheduleToggleThumbOn: {
    backgroundColor: colors.accent,
  },
  collapsibleSection: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.sm,
    gap: spacing.xs,
  },
  collapsibleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  collapsibleArrowBubble: {
    flexShrink: 0,
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collapsibleArrow: {color: colors.textMuted, fontSize: 12, fontWeight: '800'},
  collapsibleBody: {paddingTop: 2, gap: spacing.sm},
  selectorField: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  selectorValueText: {color: colors.text, fontSize: 14, fontWeight: '700'},
  selectorCaptionText: {color: colors.textMuted, fontSize: 12, marginTop: 2},
  selectorChevron: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  segmented: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  segment: {flex: 1, paddingVertical: spacing.sm, alignItems: 'center', justifyContent: 'center', minHeight: 44, paddingHorizontal: 4},
  segmentActive: {backgroundColor: colors.accentMuted},
  segmentDisabled: {opacity: 0.4},
  segmentText: {color: colors.textMuted, fontWeight: '700', fontSize: 11, textAlign: 'center'},
  segmentTextActive: {color: colors.accent},
  modePickerGrid: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  modeTile: {
    flex: 1,
    height: 40,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  modeTileActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  modeTileBar: {
    width: 3,
    alignSelf: 'stretch',
    opacity: 0.7,
  },
  modeTileBarActive: {
    opacity: 1,
  },
  modeTileContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modeTileLabel: {
    color: colors.textMuted,
    fontWeight: '700',
    fontSize: 12,
  },
  modeTileLabelActive: {
    color: colors.accent,
  },
  choiceList: {gap: spacing.xs},
  presetChoiceList: {gap: spacing.sm},
  presetCarousel: {
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    paddingVertical: 4,
  },
  presetCarouselIndicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    marginTop: spacing.xs,
  },
  presetCarouselIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.18)',
  },
  presetCarouselIndicatorActive: {
    width: 18,
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  customTextEditor: {gap: spacing.sm, marginTop: spacing.xs},
  presetCarouselCard: {
    width: 280,
    marginRight: spacing.sm,
  },
  presetChoiceCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
    gap: spacing.sm,
  },
  presetChoiceCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
    shadowColor: colors.accent,
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: {width: 0, height: 4},
    elevation: 4,
  },
  presetChoiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  presetChoiceLabel: {color: colors.text, fontSize: 13, fontWeight: '800'},
  presetChoiceLabelActive: {color: colors.accent},
  presetChoiceDescription: {color: colors.textMuted, fontSize: 11, lineHeight: 15},
  presetDiagramFrame: {
    minHeight: 68,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  presetDiagramLineBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#0C7A59',
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetDiagramLineBadgeText: {
    color: '#E8FFF8',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 21,
  },
  presetDiagramCenter: {
    flex: 1,
    justifyContent: 'center',
    gap: 1,
  },
  presetDiagramPrimaryText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 16,
  },
  presetDiagramSecondaryTextMuted: {
    opacity: 0.68,
  },
  presetDiagramSecondaryEta: {
    color: '#E8952A',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  presetDiagramRightEta: {
    color: '#E8952A',
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 21,
  },
  choiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  choiceRowActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  choiceRowCopy: {flex: 1, gap: 2},
  choiceRowLabel: {color: colors.text, fontSize: 13, fontWeight: '800'},
  choiceRowLabelActive: {color: colors.text},
  choiceRowHint: {color: colors.textMuted, fontSize: 11, lineHeight: 14},
  choiceRowHintActive: {color: colors.textMuted},
  choiceRowCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  choiceRowCheckActive: {borderColor: colors.accent, backgroundColor: colors.accent},
  choiceRowCheckText: {color: colors.background, fontSize: 11, fontWeight: '900'},
  searchRow: {flexDirection: 'row', alignItems: 'stretch', gap: spacing.xs},
  searchInput: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    color: colors.text,
    marginBottom: spacing.xs,
    minHeight: 40,
  },
  searchInputInline: {flex: 1, marginBottom: 0},
  searchDropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    minWidth: 38,
    minHeight: 40,
  },
  searchDropdownButtonCaret: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  stationListInline: {maxHeight: 220},
  stationRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: spacing.sm},
  stationName: {color: colors.text, fontSize: 14, fontWeight: '800'},
  stationMeta: {color: colors.textMuted, fontSize: 12, marginTop: 2},
  chevron: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  chevronSelected: {color: colors.accent},
  listDivider: {height: 1, backgroundColor: colors.border},
  routeGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  routeTile: {
    width: 70,
    height: 70,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  routeTileActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  routeCircle: {width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center'},
  routeCircleText: {fontWeight: '900', fontSize: 18},
  customInput: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    color: colors.text,
  },
  secondarySectionCard: {
    marginTop: spacing.xs,
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
  },
  additionalSettingsSection: {gap: spacing.sm},
  additionalSettingsTitle: {color: colors.text, fontSize: 15, fontWeight: '800'},
  additionalSettingsHint: {color: colors.textMuted, fontSize: 12},
  additionalSettingsCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'rgba(12, 16, 22, 0.82)',
    padding: spacing.sm,
    gap: spacing.xs,
  },
  additionalSettingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  additionalSettingsCopy: {flex: 1, gap: 2},
  stepperRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.md},
  stepperButton: {
    width: 36,
    height: 36,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonText: {color: colors.text, fontSize: 18, fontWeight: '800'},
  stepperButtonDisabled: {opacity: 0.45},
  stepperButtonTextDisabled: {color: colors.textMuted},
  stepperValue: {color: colors.text, fontSize: 20, fontWeight: '900', minWidth: 20, textAlign: 'center'},
  timeRangeRow: {flexDirection: 'row', gap: spacing.xs},
  dayPillRow: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, justifyContent: 'center'},
  dayPill: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    minWidth: 54,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  dayPillActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  dayPillText: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  dayPillTextActive: {color: colors.accent},
  timeStepper: {
    flex: 1,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    padding: spacing.xs,
    gap: 6,
  },
  timeStepperLabel: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  timeStepperControls: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.xs},
  timeAdjustButton: {
    width: 34,
    height: 34,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeAdjustButtonText: {color: colors.text, fontSize: 18, fontWeight: '800'},
  timeValue: {color: colors.text, fontSize: 13, fontWeight: '800'},
  saveBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.lg,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  saveButton: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  saveButtonDisabled: {opacity: 0.4},
  saveButtonSuccess: {backgroundColor: colors.success},
  saveButtonText: {color: colors.background, fontWeight: '900', fontSize: 13},
  saveHint: {color: colors.textMuted, fontSize: 12, textAlign: 'center'},
  deviceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginBottom: spacing.xs,
  },
  deviceDot: {width: 7, height: 7, borderRadius: 4, flexShrink: 0},
  deviceDotOnline: {backgroundColor: colors.success},
  deviceDotOffline: {backgroundColor: colors.warning},
  deviceLabel: {color: colors.textMuted, fontSize: 11, fontWeight: '700', flex: 1},
  deviceStatus: {fontSize: 11, fontWeight: '700'},
  deviceStatusOnline: {color: colors.success},
  deviceStatusOffline: {color: colors.warning},
  deviceChip: {
    paddingHorizontal: spacing.xs,
    paddingVertical: 3,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  deviceChipActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  deviceChipText: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  deviceChipTextActive: {color: colors.accent},
  noDeviceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xs,
    marginBottom: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.warning,
    backgroundColor: colors.surface,
  },
  noDeviceText: {color: colors.warning, fontSize: 12, fontWeight: '700'},
  liveDisabledCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.md,
    gap: spacing.xs,
  },
  liveDisabledTitle: {color: colors.text, fontSize: 14, fontWeight: '800'},
  liveDisabledBody: {color: colors.textMuted, fontSize: 12},
  emptyHint: {color: colors.textMuted, fontSize: 12},
  layoutFirstAction: {
    alignSelf: 'flex-start',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  layoutFirstActionText: {color: colors.accent, fontSize: 12, fontWeight: '700'},
  stepSection: {gap: spacing.sm},
  stepContainer: {gap: spacing.sm},
  stepNavRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  stepBackButton: {paddingVertical: 4, paddingRight: spacing.sm},
  stepBackText: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  stepTitle: {color: colors.text, fontSize: 22, fontWeight: '900', marginBottom: 4},
  stepSubtitle: {color: colors.textMuted, fontSize: 13, marginBottom: spacing.sm},
  formatCardList: {gap: spacing.sm, paddingBottom: spacing.md},
  formatCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#242933',
    backgroundColor: '#12161C',
    padding: spacing.md,
    gap: spacing.sm,
    shadowColor: '#000',
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  fmtSkel: {paddingVertical: spacing.sm, gap: 7},
  fmtSkelRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm},
  fmtSkelBadge: {
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: '#1C2330', flexShrink: 0,
  },
  fmtSkelBody: {flex: 1, gap: 5},
  fmtSkelPrimaryWrap: {
    flex: 1,
    minHeight: 22,
    borderRadius: 5,
    backgroundColor: '#1C2330',
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  fmtSkelPrimaryText: {color: '#D7DEE6', fontSize: 13, fontWeight: '700'},
  fmtSkelSecondaryWrap: {
    minHeight: 18,
    borderRadius: 5,
    backgroundColor: '#1C2330',
    paddingHorizontal: 8,
    justifyContent: 'center',
    width: '100%',
  },
  fmtSkelSecondaryText: {color: '#A9B3BE', fontSize: 13, fontWeight: '600'},
  fmtSkelEta: {
    minWidth: 30,
    height: 22,
    borderRadius: 5,
    backgroundColor: '#1C2330',
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  fmtSkelEtaText: {color: '#D7DEE6', fontSize: 10, fontWeight: '700'},
  fmtSkelChipRow: {
    flexDirection: 'row', gap: 5,
    paddingLeft: 36,
  },
  fmtSkelChip: {
    minWidth: 34, height: 18, borderRadius: 4,
    borderWidth: 1, borderColor: '#1C2330', backgroundColor: 'transparent',
    alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4,
  },
  fmtSkelChipText: {color: '#A9B3BE', fontSize: 9, fontWeight: '700'},
  formatGroup: {gap: spacing.sm},
  formatGroupSpaced: {marginTop: spacing.lg},
  formatGroupHeader: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  formatGroupLine: {flex: 1, height: 1, backgroundColor: colors.border},
  formatGroupLabel: {
    color: colors.textMuted, fontSize: 11, fontWeight: '700',
  },
  formatCardDivider: {height: 1, backgroundColor: '#262C35', marginHorizontal: -spacing.md},
  formatCardInfo: {gap: 4},
  formatCardName: {color: colors.text, fontSize: 14, fontWeight: '800'},
  formatCardDesc: {color: colors.textMuted, fontSize: 12, lineHeight: 17},
  formatCardCheck: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatCardCheckText: {color: '#fff', fontSize: 12, fontWeight: '900'},
  transitionContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.md,
  },
  transitionBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transitionBadgeText: {color: '#fff', fontSize: 28, fontWeight: '900'},
  transitionSpinnerPlaceholder: {width: 80, height: 80},
  transitionMessage: {color: colors.text, fontSize: 16, fontWeight: '700', textAlign: 'center'},
  transitionDots: {flexDirection: 'row', gap: 6},
  transitionDot: {width: 6, height: 6, borderRadius: 3, backgroundColor: colors.textMuted},
  lineGroupList: {gap: spacing.md, paddingBottom: spacing.sm},
  lineGroup: {
    paddingVertical: spacing.xs,
    alignItems: 'flex-start',
  },
  lineGroupTitle: {color: colors.textMuted, fontSize: 12, fontWeight: '700', marginBottom: spacing.sm, textAlign: 'left'},
  lineGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: spacing.xs,
    rowGap: 2,
    justifyContent: 'flex-start',
  },
  lineGridSkeleton: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: spacing.xs,
    rowGap: 2,
  },
  lineGridSkeletonTile: {width: 64, height: 54, borderRadius: radii.md, backgroundColor: colors.surface},
  lineBadgeTile: {
    width: 64,
    height: 54,
    borderRadius: radii.md,
    borderWidth: 0,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  lineBadgeTileActive: {borderColor: colors.accent, backgroundColor: 'transparent'},
  lineBadgeCircle: {width: 52, height: 52, borderRadius: 26, alignItems: 'center', justifyContent: 'center'},
  lineBadgeBusPill: {width: 54, height: 34, borderRadius: 10, paddingHorizontal: 6},
  lineBadgeCommuterRail: {width: 58, height: 52, borderRadius: 12, paddingHorizontal: 5},
  lineBadgeDiamond: {width: 44, height: 44, borderRadius: 8, transform: [{rotate: '45deg'}]},
  lineBadgeText: {fontWeight: '900', fontSize: 18},
  lineBadgeTextCompact: {fontSize: 13},
  lineBadgeBusText: {fontSize: 15, lineHeight: 18, textAlign: 'center', includeFontPadding: false},
  lineBadgeCommuterRailText: {fontSize: 11, lineHeight: 12, textAlign: 'center', includeFontPadding: false, paddingHorizontal: 2, fontWeight: '900'},
  lineBadgeTextDiamond: {transform: [{rotate: '-45deg'}]},
  stepSearchInput: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    color: colors.text,
    fontSize: 14,
  },
  stopListScroll: {maxHeight: 360},
  stopListFull: {flex: 1},
  stopListContent: {paddingBottom: 80},
  linePickerStepFull: {flex: 1},
  linePickerFullScreen: {flex: 1, paddingHorizontal: spacing.lg, paddingTop: spacing.sm},
  linePickerListScroll: {flex: 1},
  linePickerListContent: {paddingBottom: spacing.xl},
  stopPickerStepFull: {flex: 1},
  stopPickerFullScreen: {flex: 1, paddingHorizontal: spacing.lg, paddingTop: spacing.sm},
  stopSectionHeader: {color: colors.textMuted, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', paddingVertical: spacing.xs, letterSpacing: 0.5},
  stopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'transparent',
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  stopRowSelected: {backgroundColor: colors.accentMuted, borderColor: colors.accent, borderBottomColor: colors.accent},
  stopLineDot: {width: 10, height: 10, borderRadius: 5},
  stopLineDotEmpty: {width: 10, height: 10},
  stopRowInfo: {flex: 1},
  stopCheckmark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopCheckmarkText: {color: colors.background, fontSize: 12, fontWeight: '900'},
  stopPickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  stopPickerBack: {paddingVertical: 4, paddingRight: spacing.xs},
  stopPickerBackText: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  stopPickerRoute: {flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.xs},
  stopPickerBadge: {width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center'},
  stopPickerBadgeBus: {width: 40, borderRadius: 7, paddingHorizontal: 4},
  stopPickerBadgeText: {fontWeight: '900', fontSize: 11},
  stopPickerBadgeTextBus: {fontSize: 10, lineHeight: 12, includeFontPadding: false},
  stopPickerRouteName: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  stopPickerDirRow: {flexDirection: 'row', gap: 4},
  stopPickerDirPill: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: radii.sm,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  stopPickerDirPillActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  stopPickerDirText: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  stopPickerDirTextActive: {color: colors.accent},
  stopContextBar: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm},
  stopContextBadge: {width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center'},
  stopContextBadgeBus: {width: 42, borderRadius: 8, paddingHorizontal: 4},
  stopContextBadgeText: {fontWeight: '900', fontSize: 12},
  stopContextBadgeTextBus: {fontSize: 11, lineHeight: 13, includeFontPadding: false},
  stopContextLabel: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  verifyingBadge: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  doneStepContainer: {gap: spacing.sm},
  reviewEyebrow: {
    color: '#7DD3FC',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  reviewControlsCard: {
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    padding: spacing.sm,
  },
  reviewField: {gap: 6},
  reviewFieldLabel: {color: '#8EA0B4', fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5},
  reviewFieldInput: {
    minHeight: 44,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'rgba(5, 10, 16, 0.54)',
    color: colors.text,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    fontSize: 14,
    fontWeight: '700',
  },
  reviewSelectButton: {
    minHeight: 44,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: 'rgba(5, 10, 16, 0.54)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  reviewSelectButtonText: {color: '#F4F8FC', fontSize: 14, fontWeight: '900'},
  stepFooterActionRow: {
    marginTop: spacing.sm,
    alignItems: 'stretch',
    width: '100%',
  },
  doneReviewList: {gap: spacing.sm},
  reviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    backgroundColor: 'rgba(255,255,255,0.04)',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  reviewRowAccent: {
    width: 6,
    alignSelf: 'stretch',
    borderRadius: 999,
    backgroundColor: '#5CE1E6',
    opacity: 0.9,
  },
  reviewRowCopy: {flex: 1, gap: 2},
  reviewRowLabel: {color: '#8EA0B4', fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5},
  reviewRowValue: {color: '#F4F8FC', fontSize: 15, fontWeight: '900'},
  reviewRowClear: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewRowClearText: {color: '#D8E4EF', fontSize: 12, fontWeight: '900'},
  reviewActionButton: {
    alignSelf: 'stretch',
    width: '100%',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewActionButtonText: {color: colors.accent, fontSize: 13, fontWeight: '800'},
  reviewRemoveButton: {
    alignSelf: 'stretch',
    width: '100%',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: '#7F1D1D',
    backgroundColor: '#2F1212',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewRemoveButtonText: {color: '#FCA5A5', fontSize: 13, fontWeight: '900'},
  contextChipRow: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs},
  contextChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  contextChipBadge: {width: 20, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center'},
  contextChipBadgeBus: {width: 38, borderRadius: 8, paddingHorizontal: 4},
  contextChipBadgeText: {fontWeight: '900', fontSize: 10},
  contextChipBadgeTextBus: {fontSize: 9, lineHeight: 10, includeFontPadding: false},
  contextChipLabel: {color: colors.text, fontSize: 13, fontWeight: '700', maxWidth: 120},
  contextChipX: {display: 'none'},
  sectionCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  sectionTitle: {color: colors.text, fontSize: 16, fontWeight: '800', marginBottom: spacing.sm},
  payloadMeta: {color: colors.textMuted, fontSize: 11, marginTop: -spacing.xs, marginBottom: spacing.xs},
  payloadError: {color: colors.warning, fontSize: 12, marginBottom: spacing.xs},
  payloadBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    padding: spacing.sm,
  },
  payloadText: {color: colors.text, fontSize: 11, lineHeight: 16},

  // ─── Wizard Step Bar ───────────────────────────────────────────────────────
  wizardStepBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xs,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  wizardStepItem: {
    flex: 1,
    minHeight: 34,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  wizardStepItemActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  wizardStepItemComplete: {
    borderColor: colors.accent,
    backgroundColor: '#09120F',
  },
  wizardStepLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  wizardStepLabelActive: {
    color: colors.accent,
  },
  wizardStepLabelComplete: {
    color: colors.text,
  },
  wizardStepCheck: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '900',
  },

  // ─── Wizard Layout ─────────────────────────────────────────────────────────
  wizardScroll: {
    padding: spacing.lg,
    paddingBottom: 140,
    gap: spacing.md,
  },
  // Fixed preview panel (outside ScrollView)
  wizardFixedPreview: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  wizardPreviewEyebrow: {
    color: '#7DD3FC',
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  wizardPreviewWrap: {
    marginBottom: spacing.xs,
  },

  // ─── LED Style Picker ──────────────────────────────────────────────────────
  ledStylePreviewWrap: {
    marginBottom: spacing.md,
  },
  styleRowList: {gap: spacing.xs},
  styleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: radii.md,
    borderWidth: 1.5,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    minHeight: 62,
  },
  styleRowActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  styleRowBar: {
    width: 4,
    alignSelf: 'stretch',
    backgroundColor: colors.border,
    opacity: 0.5,
  },
  styleRowBarActive: {
    backgroundColor: colors.accent,
    opacity: 1,
  },
  styleRowBody: {
    flex: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    gap: 3,
  },
  styleRowLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '800',
  },
  styleRowLabelActive: {color: colors.accent},
  styleRowDesc: {
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: 15,
  },
  styleRowRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
    marginRight: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  styleRowRadioActive: {borderColor: colors.accent},
  styleRowRadioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  // ── Mini LED mockup ──────────────────────────────────────────────────────────
  mockScreen: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#04070A',
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    gap: 6,
    marginTop: 7,
    height: 30,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  mockScreenTall: {
    height: 42,
    alignItems: 'center',
  },
  mockScreenActive: {
    borderColor: 'rgba(92,225,230,0.2)',
  },
  mockBadge: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  mockBadgeText: {
    color: '#fff',
    fontSize: 7,
    fontWeight: '900',
  },
  mockCol: {
    flex: 1,
    gap: 4,
    justifyContent: 'center',
  },
  mockBar: {
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#8B9EAD',
    minWidth: 16,
  },
  mockTag: {
    width: 22,
    height: 14,
    borderRadius: 3,
    backgroundColor: '#D7E3EF',
    flexShrink: 0,
  },
  mockMiniTag: {
    width: 16,
    height: 5,
    borderRadius: 2,
    backgroundColor: '#E5C15A',
    flexShrink: 0,
  },
  mockMiniTags: {
    flexDirection: 'row',
    gap: 4,
  },
  mockTags: {
    flexDirection: 'row',
    gap: 3,
  },
  // ── Times count row ──────────────────────────────────────────────────────────
  styleTimesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  styleTimesLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  wizardConfirmBtn: {
    borderRadius: radii.md,
    backgroundColor: colors.accent,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  wizardConfirmBtnText: {
    color: colors.background,
    fontSize: 15,
    fontWeight: '900',
  },

  // ─── Wizard Review Step ────────────────────────────────────────────────────
  wizardReviewContainer: {gap: spacing.md},
  wizardSection: {gap: spacing.xs},
  wizardSectionLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  wizardNameInput: {
    height: 50,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    color: colors.text,
    paddingHorizontal: spacing.md,
    fontSize: 17,
    fontWeight: '800',
  },

  // ─── Wizard Card (shared container) ───────────────────────────────────────
  wizardCard: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  wizardCardDivider: {height: 1, backgroundColor: colors.border},
  wizardCardPadded: {padding: spacing.md, gap: spacing.xs},

  // ─── Wizard Review Rows (Your Selection) ──────────────────────────────────
  wizardReviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  wizardReviewRowCopy: {flex: 1, gap: 2},
  wizardReviewRowLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  wizardReviewRowValue: {color: colors.text, fontSize: 14, fontWeight: '800'},
  wizardReviewEditBtn: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexShrink: 0,
  },
  wizardReviewEditText: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},

  // ─── Wizard Field (Custom Text) ───────────────────────────────────────────
  wizardFieldLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  wizardFieldInput: {
    height: 40,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: spacing.sm,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },

  // ─── Wizard Settings Rows ─────────────────────────────────────────────────
  wizardSettingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  wizardSettingLabel: {color: colors.text, fontSize: 14, fontWeight: '700'},
  wizardStepper: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm},
  wizardStepperBtn: {
    width: 30,
    height: 30,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardStepperBtnDisabled: {opacity: 0.35},
  wizardStepperBtnText: {color: colors.text, fontSize: 16, fontWeight: '600'},
  wizardStepperValue: {color: colors.text, fontSize: 14, fontWeight: '800', minWidth: 40, textAlign: 'center'},
  wizardSegmented: {
    flexDirection: 'row',
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  wizardSegment: {paddingHorizontal: spacing.sm, paddingVertical: 6},
  wizardSegmentActive: {backgroundColor: colors.accentMuted},
  wizardSegmentText: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  wizardSegmentTextActive: {color: colors.accent},

  // ─── Wizard Schedule ──────────────────────────────────────────────────────
  wizardScheduleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  wizardDayRow: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  wizardDayRowDisabled: {opacity: 0.35},
  wizardDayPill: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardDayPillActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  wizardDayPillText: {color: colors.textMuted, fontSize: 9, fontWeight: '700'},
  wizardDayPillTextActive: {color: colors.accent},
  wizardTimeRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.md,
  },
});
