import {StyleSheet} from 'react-native';
import {colors, layout, radii, spacing, typography} from '../../../theme';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: colors.background},
  centeredLoadingState: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: layout.screenPadding,
  },
  loadingText: {
    color: colors.textMuted,
    fontSize: 15,
    fontWeight: '600',
  },
  keyboardAvoid: {flex: 1},
  scroll: {padding: layout.screenPadding, paddingBottom: 144, gap: layout.screenGap},
  topBarWrap: {
    backgroundColor: colors.background,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    zIndex: 30,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: layout.screenPadding,
    paddingVertical: spacing.sm,
    minHeight: layout.headerHeight,
  },
  topBarSideLeft: {
    width: 88,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  topBarSideRight: {
    width: 88,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  layoutStatusText: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  topBarCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  topBarTitle: {color: colors.text, fontSize: 16, fontWeight: '900', textAlign: 'center'},
  presetNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  presetNameTitle: {color: colors.text, fontSize: 15, fontWeight: '800', textAlign: 'center', maxWidth: 160},
  presetNameEditButton: {
    padding: spacing.xxs,
  },
  presetNameEditEmoji: {fontSize: 12, color: colors.textMuted},
  renameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.sm,
  },
  renameInput: {
    flex: 1,
    minHeight: 40,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  renameActionButton: {
    minHeight: 40,
    borderRadius: radii.md,
    backgroundColor: colors.accentMuted,
    borderWidth: 1,
    borderColor: colors.accent,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  renameActionButtonText: {color: colors.text, fontSize: 12, fontWeight: '800'},
  renameCancelButton: {
    minHeight: 40,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backButton: {
    paddingVertical: spacing.xxs,
    paddingRight: spacing.xs,
  },
  topBarBackText: {
    color: colors.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  confirmOverlay: {
    flex: 1,
    backgroundColor: colors.overlayStrong,
    justifyContent: 'center',
    paddingHorizontal: spacing.lg,
  },
  confirmSheet: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: layout.cardPadding,
  },
  confirmTitle: {color: colors.text, fontSize: 16, fontWeight: '800'},
  confirmBody: {color: colors.textMuted, fontSize: 13, marginTop: spacing.xs},
  confirmActions: {flexDirection: 'row', justifyContent: 'flex-end', gap: spacing.xs, marginTop: spacing.md},
  confirmStayButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  confirmStayText: {color: colors.text, fontSize: 13, fontWeight: '700'},
  confirmLeaveButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerSurface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  confirmLeaveText: {color: colors.dangerText, fontSize: 13, fontWeight: '700'},
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlayStrong,
    justifyContent: 'flex-start',
    paddingHorizontal: layout.screenPadding,
    paddingTop: spacing.xl,
  },
  modalBackdrop: {position: 'absolute', top: 0, right: 0, bottom: 0, left: 0},
  modalSheet: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
  },
  modalTitle: {color: colors.text, fontSize: 15, fontWeight: '800'},
  modalCloseButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerSurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalCloseButtonText: {color: colors.dangerText, fontSize: 12, fontWeight: '900'},
  modalOption: {padding: spacing.md},
  modalOptionActive: {backgroundColor: colors.accentMuted},
  modalOptionText: {color: colors.text, fontSize: 15, fontWeight: '700'},
  modalOptionTextActive: {color: colors.accent},
  layoutSelectorOverlay: {
    flex: 1,
    backgroundColor: colors.overlayStrong,
    justifyContent: 'flex-start',
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xxl + spacing.md,
  },
  selectionSheetOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  selectionSheetBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: colors.overlayStrong,
  },
  selectionSheetBackdropPressable: {flex: 1},
  selectionSheetFrame: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: spacing.sm,
    paddingBottom: spacing.sm,
    paddingTop: spacing.xl,
  },
  selectionSheetSurface: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.editorPanelBorderStrong,
    overflow: 'hidden',
    shadowColor: colors.shadow,
    shadowOpacity: 0.28,
    shadowRadius: 20,
    shadowOffset: {width: 0, height: 10},
    elevation: 10,
  },
  selectionSheetHandle: {
    alignSelf: 'center',
    width: 36,
    height: 4,
    borderRadius: 999,
    backgroundColor: colors.editorPanelBorderStrong,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
  },
  selectionSheetHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.sm,
  },
  selectionSheetHeaderCopy: {flex: 1, gap: spacing.xxs},
  selectionSheetTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
  },
  selectionSheetSubtitle: {
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  selectionSheetCloseButton: {
    minHeight: 34,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectionSheetCloseButtonText: {
    color: colors.text,
    fontSize: 12,
    fontWeight: '700',
  },
  selectionSheetOptionList: {
    marginHorizontal: spacing.xs,
    marginBottom: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  selectionSheetOption: {
    minHeight: 72,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  selectionSheetOptionActive: {
    backgroundColor: colors.selectionSurface,
  },
  selectionSheetOptionDivider: {
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  selectionSheetOptionCopy: {flex: 1, gap: 3},
  selectionSheetOptionLabel: {
    color: colors.text,
    fontSize: 15,
    fontWeight: '700',
  },
  selectionSheetOptionLabelActive: {
    color: colors.editorTextStrong,
  },
  selectionSheetOptionDescription: {
    color: colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  selectionSheetOptionDescriptionActive: {
    color: colors.editorTextSoft,
  },
  selectionSheetOptionBadge: {
    minWidth: 74,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectionSheetOptionBadgeActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentSurface,
  },
  selectionSheetOptionBadgeText: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  selectionSheetOptionBadgeTextActive: {
    color: colors.accent,
  },
  previewWrapper: {marginBottom: spacing.sm},
  stickyTopShell: {
    marginHorizontal: -spacing.lg,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.sm,
    backgroundColor: colors.background,
    zIndex: 30,
  },
  stickyPreviewShell: {
    paddingBottom: spacing.sm,
    backgroundColor: colors.background,
    zIndex: 20,
  },
  stickyPreviewHeader: {gap: spacing.xxs, marginBottom: spacing.sm, alignItems: 'center'},
  stickyPreviewEyebrow: {
    color: colors.info,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    textAlign: 'center',
  },
  previewCard: {
    borderRadius: radii.lg,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: colors.previewBorder,
    backgroundColor: colors.previewSurface,
    padding: layout.cardPaddingLg,
    minHeight: 180,
  },
  previewHeaderRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  previewStation: {color: colors.previewText, fontSize: 18, fontWeight: '900', flex: 1, marginRight: spacing.sm},
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xxs,
    borderRadius: radii.md,
  },
  statusGood: {backgroundColor: colors.successSurfacePreview},
  statusDotLarge: {width: 8, height: 8, borderRadius: 4, backgroundColor: colors.accent},
  statusPillText: {color: colors.text, fontWeight: '800', fontSize: 11},
  previewList: {marginTop: spacing.md, gap: spacing.sm},
  previewRowButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.previewBorderMuted,
    padding: spacing.sm,
    backgroundColor: colors.previewSurfaceMuted,
  },
  previewRowButtonActive: {borderColor: colors.accent, backgroundColor: colors.previewSurfaceActive},
  previewSlotBadge: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.previewBadgeBorder,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewSlotBadgeText: {color: colors.previewTextMuted, fontSize: 12, fontWeight: '800'},
  routeBadge: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: radii.md,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  routeBadgeText: {fontWeight: '900', fontSize: 16},
  routeDir: {color: colors.text, fontSize: 11, fontWeight: '700', opacity: 0.8},
  previewMain: {flex: 1, gap: 2},
  previewStationName: {fontSize: 14, fontWeight: '800'},
  previewArea: {fontSize: 12, opacity: 0.75},
  previewTimes: {fontSize: 12, fontWeight: '700'},
  card: {
    backgroundColor: 'transparent',
    borderRadius: radii.lg,
    borderWidth: 0,
    padding: 0,
    gap: spacing.sm,
  },
  builderSection: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.editorPanelBorder,
    backgroundColor: colors.editorPanelSurface,
    padding: layout.cardPaddingLg,
    gap: layout.screenGap,
    shadowColor: colors.shadow,
    shadowOpacity: 0.22,
    shadowRadius: 18,
    shadowOffset: {width: 0, height: 10},
    elevation: 6,
  },
  builderHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  builderHeaderCopy: {flex: 1, gap: spacing.xs},
  builderEyebrow: {
    color: colors.info,
    fontSize: typography.caption,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  builderTitle: {color: colors.editorTextStrong, fontSize: typography.titleLg, fontWeight: '900'},
  builderProgress: {flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'center', alignSelf: 'center', width: '100%'},
  builderProgressItem: {
    flex: 1,
    gap: spacing.xs,
    alignItems: 'center',
    position: 'relative',
    borderRadius: radii.md,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xxs,
  },
  builderProgressItemEditable: {
    borderWidth: 1,
    borderColor: 'transparent',
    backgroundColor: 'transparent',
  },
  builderProgressItemActive: {},
  builderProgressTopRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'center', width: '100%'},
  builderProgressConnector: {
    position: 'absolute',
    top: 21,
    left: '50%',
    right: '-50%',
    height: 1,
    backgroundColor: colors.editorProgressTrack,
  },
  builderProgressConnectorComplete: {backgroundColor: colors.editorProgressFill},
  builderProgressDot: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.editorPanelBorderStrong,
    backgroundColor: colors.editorProgressDotSurface,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
    elevation: 2,
  },
  builderProgressDotCenter: {
    zIndex: 3,
    elevation: 3,
  },
  builderProgressDotActive: {
    borderColor: colors.info,
    backgroundColor: colors.editorProgressDotActiveSurface,
  },
  builderProgressDotComplete: {
    borderColor: colors.accent,
    backgroundColor: colors.editorProgressDotCompleteSurface,
  },
  builderProgressDotText: {color: colors.editorTextMutedStrong, fontSize: 12, fontWeight: '900'},
  builderProgressDotTextActive: {color: colors.editorTextStrong},
  builderProgressLabel: {color: colors.editorTextSoft, fontSize: 12, fontWeight: '800', textAlign: 'center'},
  builderProgressLabelActive: {color: colors.editorTextStrong},
  builderProgressValue: {color: colors.editorTextMutedSoft, fontSize: 11, textAlign: 'center'},
  builderStepPanel: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.editorPanelBorderSoft,
    backgroundColor: colors.editorPanelSurfaceMuted,
    padding: spacing.sm,
  },
  sectionLabel: {color: colors.text, fontSize: 14, fontWeight: '800'},
  layoutRow: {flexDirection: 'row', gap: spacing.xs},
  layoutDropdownLabel: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  layoutDropdownButton: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  layoutDropdownButtonText: {color: colors.text, fontSize: 12, fontWeight: '700'},
  layoutPillTopRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xxs,
    backgroundColor: colors.accentMuted,
    borderColor: colors.accent,
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    alignSelf: 'flex-end',
  },
  layoutPillTopRightText: {color: colors.text, fontSize: 12, fontWeight: '700'},
  layoutPillChevron: {color: colors.textMuted, fontSize: 10},
  layoutPill: {
    flex: 1,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  layoutPillActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  layoutPillText: {color: colors.text, fontWeight: '700', fontSize: 13},
  layoutPillTextActive: {color: colors.accent},
  layoutHint: {color: colors.textMuted, fontSize: 12},
  editorHeader: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center'},
  sectionBlock: {gap: spacing.sm},
  sectionHint: {color: colors.textMuted, fontSize: 12},
  schedule24x7Card: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.sm,
    gap: spacing.xxs,
  },
  schedule24x7Title: {color: colors.text, fontSize: 13, fontWeight: '800'},
  schedule24x7Body: {color: colors.textMuted, fontSize: 12},
  scheduleToggleRow: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  scheduleToggleLabel: {color: colors.text, fontSize: 13, fontWeight: '800'},
  scheduleToggle: {
    width: 44,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    padding: spacing.xxs / 2,
    justifyContent: 'center',
  },
  scheduleToggleOn: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  scheduleToggleThumb: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: colors.textMuted,
  },
  scheduleToggleThumbOn: {
    backgroundColor: colors.accent,
  },
  collapsibleSection: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.md,
    gap: spacing.sm,
  },
  collapsibleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.xs,
  },
  collapsibleArrowBubble: {
    flexShrink: 0,
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  collapsibleArrow: {color: colors.textMuted, fontSize: 12, fontWeight: '800'},
  collapsibleBody: {paddingTop: spacing.xxs, gap: spacing.md},
  selectorField: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  selectorValueText: {color: colors.text, fontSize: 14, fontWeight: '700'},
  selectorCaptionText: {color: colors.textMuted, fontSize: 12, marginTop: spacing.xxs},
  selectorChevron: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  segmented: {
    flexDirection: 'row',
    backgroundColor: colors.background,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  segment: {
    flex: 1,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: layout.buttonHeight,
    paddingHorizontal: spacing.xxs,
  },
  segmentActive: {backgroundColor: colors.accentMuted},
  segmentDisabled: {opacity: 0.4},
  segmentText: {color: colors.textMuted, fontWeight: '700', fontSize: 11, textAlign: 'center'},
  segmentTextActive: {color: colors.accent},
  modePickerGrid: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  modeTile: {
    flex: 1,
    height: 44,
    borderRadius: 10,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.border,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  modeTileActive: {
    borderColor: colors.accent,
    backgroundColor: colors.surface,
  },
  modeTileBar: {
    width: 4,
    alignSelf: 'stretch',
    opacity: 1,
  },
  modeTileBarActive: {
    opacity: 1,
  },
  modeTileContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
  },
  modeTileLabel: {
    color: colors.textSecondary,
    fontWeight: '600',
    fontSize: 14,
  },
  modeTileLabelActive: {
    color: colors.accent,
  },
  nycBrandStrip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  nycBrandLogoPlate: {
    minWidth: 68,
    minHeight: 36,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    paddingVertical: 6,
  },
  nycBrandLogo: {},
  nycBrandCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  nycBrandEyebrow: {
    color: colors.accent,
    fontSize: 12,
    fontWeight: '600',
  },
  nycBrandLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  servicePickerList: {
    gap: spacing.sm,
  },
  servicePickerCard: {
    flexDirection: 'row',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    overflow: 'hidden',
  },
  servicePickerCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.surface,
  },
  servicePickerAccent: {
    width: 4,
    alignSelf: 'stretch',
  },
  servicePickerBody: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
  },
  servicePickerIdentity: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minWidth: 0,
  },
  servicePickerLogoPlate: {
    minWidth: 72,
    minHeight: 40,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    paddingVertical: 6,
  },
  servicePickerBadge: {
    borderRadius: radii.sm,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    minWidth: 80,
  },
  servicePickerBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  servicePickerCopy: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  servicePickerTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  servicePickerTitleActive: {
    color: colors.accent,
  },
  servicePickerDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  choiceList: {gap: spacing.xs},
  presetChoiceList: {gap: spacing.sm},
  presetCarousel: {
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    paddingVertical: spacing.xs,
  },
  presetCarouselIndicators: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  presetCarouselIndicator: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.editorAccentGhost,
  },
  presetCarouselIndicatorActive: {
    width: 18,
    borderRadius: 999,
    backgroundColor: colors.accent,
  },
  customTextEditor: {gap: spacing.sm, marginTop: spacing.sm},
  presetCarouselCard: {
    width: 280,
    marginRight: spacing.sm,
  },
  presetChoiceCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.md,
  },
  presetChoiceCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  presetChoiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  presetChoiceLabel: {color: colors.text, fontSize: 13, fontWeight: '800'},
  presetChoiceLabelActive: {color: colors.accent},
  presetChoiceDescription: {color: colors.textMuted, fontSize: 11, lineHeight: 15},
  presetDiagramFrame: {
    minHeight: 68,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  presetDiagramLineBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.routeFallback,
    alignItems: 'center',
    justifyContent: 'center',
  },
  presetDiagramLineBadgeText: {
    color: colors.routeFallbackText,
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 21,
  },
  presetDiagramCenter: {flex: 1, justifyContent: 'center', gap: spacing.xxs},
  presetDiagramPrimaryText: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 16,
  },
  presetDiagramSecondaryTextMuted: {
    opacity: 0.68,
  },
  presetDiagramSecondaryEta: {
    color: colors.highlight,
    fontSize: 12,
    fontWeight: '700',
    marginTop: 2,
  },
  presetDiagramRightEta: {
    color: colors.highlight,
    fontSize: 18,
    fontWeight: '700',
    lineHeight: 21,
  },
  choiceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.md,
  },
  choiceRowActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  choiceRowCopy: {flex: 1, gap: spacing.xxs},
  choiceRowLabel: {color: colors.text, fontSize: 13, fontWeight: '800'},
  choiceRowLabelActive: {color: colors.text},
  choiceRowHint: {color: colors.textMuted, fontSize: 11, lineHeight: 14},
  choiceRowHintActive: {color: colors.textMuted},
  choiceRowCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
  },
  choiceRowCheckActive: {borderColor: colors.accent, backgroundColor: colors.accent},
  choiceRowCheckText: {color: colors.onAccent, fontSize: 11, fontWeight: '900'},
  searchRow: {flexDirection: 'row', alignItems: 'stretch', gap: spacing.sm},
  searchInput: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    color: colors.text,
    marginBottom: spacing.sm,
    minHeight: 40,
  },
  searchInputInline: {flex: 1, marginBottom: 0},
  searchDropdownButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    minWidth: 38,
    minHeight: 40,
  },
  searchDropdownButtonCaret: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  stationListInline: {maxHeight: 220},
  stationRow: {flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: spacing.sm},
  stationName: {color: colors.text, fontSize: 16, fontWeight: '700'},
  stationMeta: {color: colors.textSecondary, fontSize: 13},
  chevron: {color: colors.textSecondary, fontSize: 22, fontWeight: '400'},
  chevronSelected: {color: colors.accent},
  listDivider: {height: 1, backgroundColor: colors.border},
  routeGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm},
  routeTile: {
    width: 70,
    height: 70,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.background,
  },
  routeTileActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  routeCircle: {width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center'},
  routeCircleText: {fontWeight: '900', fontSize: 18},
  customInput: {
    backgroundColor: colors.surface,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    color: colors.text,
  },
  secondarySectionCard: {
    marginTop: spacing.sm,
    gap: spacing.md,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: spacing.md,
  },
  additionalSettingsSection: {gap: spacing.sm},
  additionalSettingsTitle: {color: colors.text, fontSize: 15, fontWeight: '800'},
  additionalSettingsHint: {color: colors.textMuted, fontSize: 12},
  additionalSettingsCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.editorPanelSurfaceStrong,
    padding: spacing.md,
    gap: spacing.sm,
  },
  additionalSettingsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  additionalSettingsCopy: {flex: 1, gap: spacing.xxs},
  stepperRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.md},
  stepperButton: {
    width: 36,
    height: 36,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepperButtonText: {color: colors.text, fontSize: 18, fontWeight: '800'},
  stepperButtonDisabled: {opacity: 0.45},
  stepperButtonTextDisabled: {color: colors.textMuted},
  stepperValue: {color: colors.text, fontSize: 20, fontWeight: '900', minWidth: 20, textAlign: 'center'},
  timeRangeRow: {flexDirection: 'row', gap: spacing.xs},
  dayPillRow: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, justifyContent: 'center'},
  dayPill: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    minWidth: 54,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    paddingVertical: spacing.xs,
  },
  dayPillActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  dayPillText: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  dayPillTextActive: {color: colors.accent},
  timeStepper: {
    flex: 1,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    padding: spacing.xs,
    gap: 6,
  },
  timeStepperLabel: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  timeStepperControls: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: spacing.xs},
  timeAdjustButton: {
    width: 34,
    height: 34,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeAdjustButtonText: {color: colors.text, fontSize: 18, fontWeight: '800'},
  timeValue: {color: colors.text, fontSize: 13, fontWeight: '800'},
  saveBar: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: spacing.md,
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.lg,
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderColor: colors.border,
    gap: spacing.sm,
  },
  saveButton: {
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
  },
  saveButtonDisabled: {opacity: 0.4},
  saveButtonSuccess: {backgroundColor: colors.success},
  saveButtonText: {color: colors.onAccent, fontWeight: '900', fontSize: 13},
  saveHint: {color: colors.textMuted, fontSize: 12, textAlign: 'center'},
  deviceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    marginBottom: spacing.xs,
  },
  deviceDot: {width: 7, height: 7, borderRadius: 4, flexShrink: 0},
  deviceDotOnline: {backgroundColor: colors.success},
  deviceDotOffline: {backgroundColor: colors.warning},
  deviceLabel: {color: colors.textMuted, fontSize: 11, fontWeight: '700', flex: 1},
  deviceStatus: {fontSize: 11, fontWeight: '700'},
  deviceStatusOnline: {color: colors.success},
  deviceStatusOffline: {color: colors.warning},
  deviceChip: {
    paddingHorizontal: spacing.xs,
    paddingVertical: 3,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
  },
  deviceChipActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  deviceChipText: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  deviceChipTextActive: {color: colors.accent},
  noDeviceBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xs,
    marginBottom: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.warning,
    backgroundColor: colors.surface,
  },
  noDeviceText: {color: colors.warning, fontSize: 12, fontWeight: '700'},
  liveDisabledCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    padding: spacing.md,
    gap: spacing.xs,
  },
  liveDisabledTitle: {color: colors.text, fontSize: 14, fontWeight: '800'},
  liveDisabledBody: {color: colors.textMuted, fontSize: 12},
  emptyHint: {color: colors.textMuted, fontSize: 12},
  layoutFirstAction: {
    alignSelf: 'flex-start',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  layoutFirstActionText: {color: colors.accent, fontSize: 12, fontWeight: '700'},
  stepSection: {gap: spacing.sm},
  cityPickerSection: {gap: spacing.md},
  stepContainer: {gap: spacing.md},
  stepNavRow: {flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between'},
  stepBackButton: {paddingVertical: 4, paddingRight: spacing.sm},
  stepBackText: {color: colors.textMuted, fontSize: 13, fontWeight: '700'},
  stepTitleRow: {flexDirection: 'row' as const, alignItems: 'center' as const, gap: spacing.sm},
  stepTitleRule: {width: 24, height: 1.5, backgroundColor: colors.accent, borderRadius: 1},
  stepTitle: {
    color: colors.accent,
    fontSize: 13,
    fontWeight: '700' as const,
    letterSpacing: 1.6,
    textTransform: 'uppercase' as const,
  },
  stepSubtitle: {color: colors.text, fontSize: 20, fontWeight: '700' as const, lineHeight: 26},
  cityPickerList: {gap: spacing.sm, paddingBottom: spacing.md},
  cityPickerCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.md,
    paddingVertical: 14,
    gap: spacing.xs,
  },
  cityPickerCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  cityPickerCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  cityPickerIdentity: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flex: 1,
  },
  cityPickerAgencyPill: {
    minWidth: 52,
    minHeight: 28,
    borderRadius: radii.sm,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  cityPickerAgencyText: {
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.4,
  },
  cityPickerTitleWrap: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
  },
  cityPickerTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  cityPickerTitleActive: {
    color: colors.text,
  },
  cityPickerCopy: {gap: spacing.xxs},
  cityPickerProvider: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  cityPickerDescription: {
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
  },
  formatCardList: {gap: spacing.sm, paddingBottom: spacing.md},
  formatCard: {
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.editorFormatCardBorder,
    backgroundColor: colors.editorFormatCardSurface,
    padding: spacing.md,
    gap: spacing.sm,
    shadowColor: colors.shadow,
    shadowOpacity: 0.16,
    shadowRadius: 8,
    shadowOffset: {width: 0, height: 2},
    elevation: 2,
  },
  fmtSkel: {paddingVertical: spacing.sm, gap: 7},
  fmtSkelRow: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm},
  fmtSkelBadge: {
    width: 28, height: 28, borderRadius: 14,
    backgroundColor: colors.editorFormatSkeleton, flexShrink: 0,
  },
  fmtSkelBody: {flex: 1, gap: 5},
  fmtSkelPrimaryWrap: {
    flex: 1,
    minHeight: 22,
    borderRadius: 5,
    backgroundColor: colors.editorFormatSkeleton,
    paddingHorizontal: 8,
    justifyContent: 'center',
  },
  fmtSkelPrimaryText: {color: colors.editorTextSoft, fontSize: 13, fontWeight: '700'},
  fmtSkelSecondaryWrap: {
    minHeight: 18,
    borderRadius: 5,
    backgroundColor: colors.editorFormatSkeleton,
    paddingHorizontal: 8,
    justifyContent: 'center',
    width: '100%',
  },
  fmtSkelSecondaryText: {color: colors.editorTextMutedSoft, fontSize: 13, fontWeight: '600'},
  fmtSkelEta: {
    minWidth: 30,
    height: 22,
    borderRadius: 5,
    backgroundColor: colors.editorFormatSkeleton,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  fmtSkelEtaText: {color: colors.editorTextSoft, fontSize: 10, fontWeight: '700'},
  fmtSkelChipRow: {
    flexDirection: 'row', gap: 5,
    paddingLeft: 36,
  },
  fmtSkelChip: {
    minWidth: 34, height: 18, borderRadius: 4,
    borderWidth: 1, borderColor: colors.editorFormatSkeleton, backgroundColor: 'transparent',
    alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4,
  },
  fmtSkelChipText: {color: colors.editorTextMutedSoft, fontSize: 9, fontWeight: '700'},
  formatGroup: {gap: spacing.sm},
  formatGroupSpaced: {marginTop: spacing.lg},
  formatGroupHeader: {
    flexDirection: 'row', alignItems: 'center', gap: spacing.sm,
    marginBottom: spacing.xs,
  },
  formatGroupLine: {flex: 1, height: 1, backgroundColor: colors.border},
  formatGroupLabel: {
    color: colors.textMuted, fontSize: 11, fontWeight: '700',
  },
  formatCardDivider: {height: 1, backgroundColor: colors.editorFormatDivider, marginHorizontal: -spacing.md},
  formatCardInfo: {gap: 4},
  formatCardName: {color: colors.text, fontSize: 14, fontWeight: '800'},
  formatCardDesc: {color: colors.textMuted, fontSize: 12, lineHeight: 17},
  formatCardCheck: {
    position: 'absolute',
    top: spacing.sm,
    right: spacing.sm,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  formatCardCheckText: {color: colors.editorTextStrongAlt, fontSize: 12, fontWeight: '900'},
  transitionContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xl,
    gap: spacing.md,
  },
  transitionBadge: {
    width: 80,
    height: 80,
    borderRadius: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  transitionBadgeText: {color: colors.editorTextStrongAlt, fontSize: 28, fontWeight: '900'},
  transitionSpinnerPlaceholder: {width: 80, height: 80},
  transitionMessage: {color: colors.text, fontSize: 16, fontWeight: '700', textAlign: 'center'},
  transitionDots: {flexDirection: 'row', gap: 6},
  transitionDot: {width: 6, height: 6, borderRadius: 3, backgroundColor: colors.textMuted},
  lineGroupList: {gap: spacing.md, paddingBottom: spacing.sm},
  lineGroupListSubway: {
    gap: spacing.sm,
    alignItems: 'flex-start',
  },
  lineGroup: {
    alignItems: 'flex-start',
  },
  lineGroupSubway: {
    width: '100%',
    alignItems: 'flex-start',
  },
  lineGroupTitle: {color: colors.textSecondary, fontSize: 13, fontWeight: '600', marginBottom: spacing.sm, textAlign: 'left'},
  lineGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: spacing.sm,
    rowGap: spacing.md,
    justifyContent: 'flex-start',
  },
  lineGridBus: {
    justifyContent: 'space-between',
    columnGap: 0,
    rowGap: 4,
  },
  lineGridSubway: {
    width: '100%',
    justifyContent: 'flex-start',
  },
  lineGridChicagoTrain: {
    justifyContent: 'space-between',
    columnGap: 0,
  },
  lineGridSkeleton: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: spacing.xs,
    rowGap: 2,
  },
  chicagoLineList: {
    width: '100%',
    gap: spacing.xs,
  },
  chicagoLineOptionGroup: {
    gap: spacing.xs,
  },
  chicagoLineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    overflow: 'hidden',
    minHeight: layout.buttonHeight,
  },
  chicagoLineRowSelected: {
    borderWidth: 1.5,
  },
  chicagoLineAccentBar: {
    width: 4,
    alignSelf: 'stretch',
  },
  chicagoLineRowBody: {
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  chicagoLineRowText: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  chicagoLineDropdownButton: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chicagoLineRowChevron: {
    fontSize: 18,
    lineHeight: 20,
    fontWeight: '300',
  },
  chicagoPatternInlineList: {
    marginLeft: 4,
    borderLeftWidth: 3,
    borderLeftColor: colors.border,
    paddingLeft: spacing.sm,
  },
  chicagoPatternInlineOption: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 44,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  chicagoPatternInlineOptionActive: {
    backgroundColor: colors.selectionSurface,
  },
  chicagoPatternInlineText: {
    color: colors.text,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '600',
  },
  chicagoPatternOptionInner: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    minWidth: 0,
  },
  chicagoPatternRouteRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    minWidth: 0,
  },
  chicagoPatternEndpoint: {
    color: colors.textSecondary,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
    flexShrink: 1,
  },
  chicagoPatternEndpointStart: {},
  chicagoPatternEndpointEnd: {
    color: colors.text,
    fontWeight: '700',
    flexShrink: 1,
  },
  chicagoPatternArrow: {
    color: colors.textTertiary,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '400',
    flexShrink: 0,
  },
  chicagoPatternCheck: {
    width: 20,
    height: 20,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: spacing.xs,
  },
  chicagoPatternCheckActive: {
    backgroundColor: colors.accent,
  },
  chicagoPatternCheckText: {
    color: '#FFFFFF',
    fontSize: 13,
    lineHeight: 15,
    fontWeight: '900',
  },
  bostonRouteCardList: {
    gap: spacing.xs,
    width: '100%',
  },
  bostonRouteCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    width: '100%',
    minHeight: 76,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.editorPanelBorder,
    backgroundColor: colors.editorPanelSurfaceCard,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  bostonRouteCardActive: {
    borderColor: colors.accent,
    backgroundColor: colors.editorPanelSurfaceActive,
  },
  bostonRouteCardAccent: {
    width: 4,
    alignSelf: 'stretch',
    borderRadius: 999,
    opacity: 0.72,
  },
  bostonRouteCardAccentActive: {
    opacity: 1,
  },
  chicagoBusList: {
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.editorPanelBorder,
    backgroundColor: colors.editorPanelSurfaceCard,
    overflow: 'hidden',
    width: '100%',
  },
  chicagoBusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    minHeight: 64,
    paddingRight: spacing.md,
  },
  chicagoBusRowActive: {
    backgroundColor: colors.accentSurface,
  },
  chicagoBusRowDivider: {
    height: 1,
    backgroundColor: colors.editorPanelBorder,
    marginLeft: 72,
  },
  chicagoBusAccentBar: {
    width: 4,
    alignSelf: 'stretch',
    minHeight: 64,
    borderTopLeftRadius: 0,
    borderBottomLeftRadius: 0,
  },
  chicagoBusBadgeWrap: {
    width: 52,
    height: 64,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  chicagoBusCardBadge: {
    minWidth: 36,
    height: 28,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 7,
    flexShrink: 0,
  },
  chicagoBusCardBadgeText: {
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: 0.2,
  },
  chicagoBusName: {
    flex: 1,
    minWidth: 0,
    color: colors.editorTextStrong,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  chicagoBusNameActive: {
    color: colors.accent,
  },
  chicagoBusCheck: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1.5,
    borderColor: colors.editorPanelBorder,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  chicagoBusCheckActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  chicagoBusCheckText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '900',
    lineHeight: 13,
  },
  bostonRouteCardBadge: {
    width: 58,
    height: 58,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.xs,
    flexShrink: 0,
  },
  bostonRouteCardBadgeText: {
    fontSize: 19,
    fontWeight: '900',
    textAlign: 'center',
    letterSpacing: -0.3,
  },
  bostonRouteCardBadgeTextCompact: {
    fontSize: 15,
    lineHeight: 17,
    includeFontPadding: false,
  },
  bostonRouteCardCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  bostonRouteCardTitle: {
    color: colors.editorTextStrong,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  bostonRouteCardTitleActive: {
    color: colors.editorTextStrongAlt,
  },
  bostonRouteCardSubtitle: {
    color: colors.editorTextMutedSoft,
    fontSize: 12,
    lineHeight: 17,
  },
  bostonRouteCardSubtitleActive: {
    color: colors.editorTextSoftAlt,
  },
  lineBadgeTileWrapChicagoTrain: {
    width: '48%',
  },
  lineGridSkeletonTile: {width: 60, height: 60, borderRadius: radii.md, backgroundColor: colors.surface},
  lineBadgeTile: {
    width: 60,
    height: 60,
    borderRadius: radii.md,
    borderWidth: 0,
    borderColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  lineBadgeTileSubway: {
    width: 56,
    height: 56,
  },
  lineBadgeTileBus: {
    height: 55,
  },
  lineBadgeTileChicagoTrain: {
    width: '100%',
    height: 54,
  },
  lineBadgeTileActive: {borderColor: colors.accent, backgroundColor: 'transparent'},
  lineBadgeCircle: {width: 48, height: 48, borderRadius: 24, alignItems: 'center', justifyContent: 'center'},
  lineBadgeBusPill: {width: 54, height: 34, borderRadius: 10, paddingHorizontal: 6},
  lineBadgeChicagoTrainPill: {width: '100%', height: 44, borderRadius: 14, paddingHorizontal: 12},
  lineBadgeCommuterRail: {width: 58, height: 52, borderRadius: 12, paddingHorizontal: 5},
  lineBadgeDiamond: {width: 44, height: 44, borderRadius: 8, transform: [{rotate: '45deg'}]},
  lineBadgeText: {fontWeight: '900', fontSize: 18},
  lineBadgeTextCompact: {fontSize: 13},
  lineBadgeBusText: {fontSize: 15, lineHeight: 18, textAlign: 'center', includeFontPadding: false},
  lineBadgeChicagoTrainText: {fontSize: 16, lineHeight: 18, textAlign: 'center', includeFontPadding: false},
  lineBadgeCommuterRailText: {fontSize: 11, lineHeight: 12, textAlign: 'center', includeFontPadding: false, paddingHorizontal: 2, fontWeight: '900'},
  lineBadgeTextDiamond: {transform: [{rotate: '-45deg'}]},
  lirrBranchList: {gap: spacing.xs, width: '100%'},
  lirrBranchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 56,
    borderRadius: radii.lg,
    borderWidth: 1,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    gap: spacing.sm,
  },
  lirrBranchRowSelected: {borderWidth: 2},
  lirrBranchName: {flexShrink: 1, fontSize: 14, lineHeight: 18, fontWeight: '700'},
  lirrBranchNameSelected: {color: colors.editorTextStrongAlt, fontWeight: '700'},
  lirrBranchCheck: {fontSize: 16, fontWeight: '700'},
  stepSearchInput: {
    backgroundColor: colors.background,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingVertical: 12,
    color: colors.text,
    fontSize: 16,
    fontWeight: '500',
  },
  stepSearchField: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingLeft: spacing.sm,
    paddingRight: spacing.md,
  },
  stepSearchIcon: {
    marginRight: spacing.xs,
  },
  stepSearchInputWithIcon: {
    flex: 1,
    color: colors.text,
    fontSize: 16,
    fontWeight: '500',
    paddingVertical: 12,
  },
  stopListScroll: {maxHeight: 360},
  stopListFull: {flex: 1},
  stopListContent: {paddingBottom: 80},
  linePickerStepFull: {flex: 1},
  linePickerFullScreen: {flex: 1, paddingHorizontal: spacing.lg, paddingTop: spacing.lg},
  linePickerListScroll: {flex: 1},
  linePickerListContent: {paddingTop: 0, paddingBottom: spacing.xl},
  lirrStationHeader: {fontSize: 13, fontWeight: '600', color: colors.textMuted, paddingBottom: spacing.xs},
  lirrStationBackRow: {flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.sm},
  lirrStationBackText: {fontSize: 14, fontWeight: '600', color: colors.accent},
  stopPickerStepFull: {flex: 1},
  stopPickerFullScreen: {flex: 1, paddingHorizontal: spacing.lg, paddingTop: spacing.lg},
  stopSectionHeader: {color: colors.textMuted, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', paddingVertical: spacing.xs, letterSpacing: 0.5},
  boroughHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 56,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
  },
  boroughHeaderSelected: {
    borderColor: colors.accent,
    backgroundColor: colors.selectionSurfaceStrong,
  },
  boroughHeaderText: {
    flex: 1,
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  boroughHeaderTextSelected: {
    color: colors.accent,
  },
  boroughHeaderMeta: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '500',
    marginRight: spacing.xs,
  },
  boroughChevron: {
    color: colors.textMuted,
    fontSize: 14,
    width: 16,
    textAlign: 'center',
  },
  boroughAccentPip: {
    width: 4,
    height: 20,
    borderRadius: 2,
    marginRight: spacing.sm,
    flexShrink: 0,
  },
  stopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    minHeight: 52,
    paddingLeft: 12,
    paddingRight: spacing.md,
    paddingVertical: spacing.xs,
    borderLeftWidth: 5,
    borderLeftColor: 'transparent',
    borderRadius: radii.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  stopRowSelected: {backgroundColor: colors.warningSurface, borderLeftColor: colors.accent},
  stopLineDot: {width: 10, height: 10, borderRadius: 5},
  stopLineDotEmpty: {width: 10, height: 10},
  stopRowInfo: {flex: 1, gap: 2},
  stationLineSummary: {color: colors.accent, fontSize: 11, fontWeight: '700', marginTop: 4},
  stopCheckmark: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopCheckmarkText: {color: colors.onAccent, fontSize: 12, fontWeight: '900'},
  stopPickerHeader: {gap: spacing.sm},
  stopPickerBack: {paddingVertical: 4, paddingRight: spacing.xs},
  stopPickerRoute: {flex: 1, flexDirection: 'row', alignItems: 'center', gap: spacing.xs},
  stopPickerBadge: {width: 26, height: 26, borderRadius: 13, alignItems: 'center', justifyContent: 'center'},
  stopPickerBadgeBus: {width: 40, borderRadius: 7, paddingHorizontal: 4},
  stopPickerBadgeText: {fontWeight: '900', fontSize: 11},
  stopPickerBadgeTextBus: {fontSize: 10, lineHeight: 12, includeFontPadding: false},
  stopPickerRouteName: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  stopPickerDirRow: {flexDirection: 'row', gap: spacing.xs, alignSelf: 'stretch'},
  stopPickerDirRowChicagoTrain: {width: '100%', alignSelf: 'stretch'},
  stopPickerDirPill: {
    flex: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    borderRadius: 10,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 64,
    justifyContent: 'center',
    alignItems: 'center',
  },
  stopPickerDirPillChicagoTrain: {
    flex: 1,
    minHeight: 64,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.xs,
  },
  stopPickerDirPillActive: {borderColor: colors.accent, backgroundColor: colors.selectionSurface},
  stopPickerDirCopy: {alignItems: 'center', gap: 3, minWidth: 0},
  stopPickerDirText: {color: colors.text, fontSize: 15, fontWeight: '700', lineHeight: 18},
  stopPickerDirTextChicagoTrain: {textAlign: 'center'},
  stopPickerDirTextBoston: {textAlign: 'center'},
  stopPickerDirTextActive: {color: colors.accent},
  stopPickerDirTerminal: {color: colors.textTertiary, fontSize: 12, lineHeight: 14, textAlign: 'center'},
  stopPickerDirTerminalActive: {color: colors.textTertiary},
  stopContextBar: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm},
  stopContextBadge: {width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center'},
  stopContextBadgeBus: {width: 42, borderRadius: 8, paddingHorizontal: 4},
  stopContextBadgeText: {fontWeight: '900', fontSize: 12},
  stopContextBadgeTextBus: {fontSize: 11, lineHeight: 13, includeFontPadding: false},
  stopContextLabel: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  verifyingBadge: {color: colors.textMuted, fontSize: 11, fontWeight: '700'},
  doneStepContainer: {gap: spacing.sm},
  reviewEyebrow: {
    color: colors.info,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  reviewControlsCard: {
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.editorPanelBorder,
    backgroundColor: colors.glassSurface,
    padding: spacing.sm,
  },
  reviewField: {gap: 6},
  reviewFieldLabel: {color: colors.editorTextMutedSoft, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5},
  reviewFieldInput: {
    minHeight: 44,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.editorPanelSurfaceMuted,
    color: colors.text,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    fontSize: 14,
    fontWeight: '700',
  },
  reviewSelectButton: {
    minHeight: 44,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.editorPanelSurfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  reviewSelectButtonText: {color: colors.editorTextStrong, fontSize: 14, fontWeight: '900'},
  stepFooterActionRow: {
    marginTop: spacing.sm,
    alignItems: 'stretch',
    width: '100%',
  },
  doneReviewList: {gap: spacing.sm},
  reviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.editorPanelBorder,
    backgroundColor: colors.glassSurface,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
  },
  reviewRowAccent: {
    width: 6,
    alignSelf: 'stretch',
    borderRadius: 999,
    backgroundColor: colors.accent,
    opacity: 0.9,
  },
  reviewRowCopy: {flex: 1, gap: 2},
  reviewRowLabel: {color: colors.editorTextMutedSoft, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 0.5},
  reviewRowValue: {color: colors.editorTextStrong, fontSize: 15, fontWeight: '900'},
  reviewRowClear: {
    width: 30,
    height: 30,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: colors.editorPanelBorderInteractive,
    backgroundColor: colors.glassSurfaceStrong,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewRowClearText: {color: colors.editorTextSoft, fontSize: 12, fontWeight: '900'},
  reviewActionButton: {
    alignSelf: 'stretch',
    width: '100%',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewActionButtonText: {color: colors.accent, fontSize: 13, fontWeight: '800'},
  reviewRemoveButton: {
    alignSelf: 'stretch',
    width: '100%',
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerSurface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewRemoveButtonText: {color: colors.dangerText, fontSize: 13, fontWeight: '900'},
  contextChipRow: {flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs},
  contextChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.sm,
    paddingVertical: 6,
  },
  contextChipBadge: {width: 20, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center'},
  contextChipBadgeBus: {width: 38, borderRadius: 8, paddingHorizontal: 4},
  contextChipBadgeText: {fontWeight: '900', fontSize: 10},
  contextChipBadgeTextBus: {fontSize: 9, lineHeight: 10, includeFontPadding: false},
  contextChipLabel: {color: colors.text, fontSize: 13, fontWeight: '700', maxWidth: 120},
  contextChipX: {display: 'none'},
  sectionCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.lg,
    padding: spacing.md,
    marginBottom: spacing.sm,
  },
  sectionTitle: {color: colors.text, fontSize: 16, fontWeight: '800', marginBottom: spacing.sm},
  payloadMeta: {color: colors.textMuted, fontSize: 11, marginTop: -spacing.xs, marginBottom: spacing.xs},
  payloadError: {color: colors.warning, fontSize: 12, marginBottom: spacing.xs},
  payloadBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radii.md,
    backgroundColor: colors.surface,
    padding: spacing.sm,
  },
  payloadText: {color: colors.text, fontSize: 11, lineHeight: 16},

  // ─── Wizard Step Bar ───────────────────────────────────────────────────────
  wizardStepBar: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  stepIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  stepDotWrapper: {
    alignItems: 'center',
    width: 56,
  },
  stepDotCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepDotCircleActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  stepDotCircleComplete: {
    borderColor: colors.accent,
    backgroundColor: colors.accent,
  },
  stepDotNumber: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  stepDotNumberActive: {
    color: colors.accent,
  },
  stepDotCheckmark: {
    color: colors.onAccent,
    fontSize: 12,
    fontWeight: '900',
  },
  stepDotLabel: {
    color: colors.textMuted,
    fontSize: 10,
    fontWeight: '600',
    marginTop: 5,
    textAlign: 'center',
  },
  stepDotLabelActive: {
    color: colors.accent,
  },
  stepDotLabelComplete: {
    color: colors.text,
  },
  stepConnectorTrack: {
    flex: 1,
    height: 2,
    marginTop: 13,
    backgroundColor: colors.border,
    overflow: 'hidden',
    borderRadius: 1,
  },
  stepConnectorFill: {
    height: '100%',
    backgroundColor: colors.accent,
    borderRadius: 1,
  },

  // ─── Wizard Layout ─────────────────────────────────────────────────────────
  wizardScroll: {
    padding: spacing.lg,
    paddingTop: spacing.sm,
    paddingBottom: 140,
    gap: spacing.md,
  },
  // Fixed preview panel (outside ScrollView)
  wizardFixedPreview: {
    paddingHorizontal: 32,
    paddingTop: spacing.sm,
    paddingBottom: 0,
    backgroundColor: colors.surface,
  },
  editorPreviewCarousel: {
    gap: spacing.xs,
  },
  editorPreviewStage: {
    position: 'relative',
    overflow: 'visible',
  },
  editorPreviewPane: {
    width: '100%',
  },
  editorPreviewPaneHidden: {
    opacity: 0,
  },
  editorPreviewPaneFloating: {
    position: 'absolute',
    left: 0,
    top: 0,
    right: 0,
  },
  editorPreviewNavRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
    paddingHorizontal: spacing.xs,
    paddingTop: spacing.xs,
  },
  editorPreviewArrowButton: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editorPreviewNavCenter: {
    flex: 1,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  editorPreviewNavTitle: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '800',
  },
  editorPreviewNavMeta: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
  },
  editorPreviewDots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    paddingBottom: spacing.xs,
  },
  editorPreviewDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.border,
  },
  editorPreviewDotActive: {
    width: 16,
    backgroundColor: colors.accent,
  },
  wizardPreviewEyebrow: {
    color: colors.info,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  wizardPreviewWrap: {
    marginBottom: spacing.xs,
  },

  // ─── LED Style Picker ──────────────────────────────────────────────────────
  ledStylePreviewWrap: {
    marginBottom: spacing.md,
  },
  styleRowList: {gap: spacing.xs},
  styleRow: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    minHeight: 72,
    paddingHorizontal: spacing.sm,
    paddingVertical: 10,
  },
  styleRowActive: {
    borderColor: colors.accent,
    borderWidth: 2,
    backgroundColor: colors.surface,
  },
  styleRowBar: {
    width: 4,
    alignSelf: 'stretch',
    backgroundColor: colors.border,
    opacity: 0.5,
  },
  styleRowBarActive: {
    backgroundColor: colors.accent,
    opacity: 1,
  },
  styleRowBody: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  styleRowLabel: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
    flex: 1,
  },
  styleRowLabelActive: {color: colors.accent},
  styleRowPreview: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  styleRowDesc: {
    color: colors.textMuted,
    fontSize: 11,
    lineHeight: 15,
  },
  styleRowRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: colors.border,
    marginRight: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
  },
  styleRowRadioActive: {borderColor: colors.accent},
  styleRowRadioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.accent,
  },
  // ── Mini LED mockup ──────────────────────────────────────────────────────────
  mockScreen: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.editorMockSurface,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    gap: 8,
    height: 36,
    borderWidth: 1,
    borderColor: colors.editorMockBorder,
  },
  mockScreenTall: {
    height: 60,
    alignItems: 'center',
  },
  mockScreenActive: {
    borderColor: colors.editorMockBorderActive,
  },
  mockBadge: {
    width: 22,
    height: 22,
    borderRadius: 11,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  mockBadgePill: {
    width: 30,
    height: 20,
    borderRadius: 7,
    paddingHorizontal: 4,
  },
  mockBadgeRail: {
    width: 32,
    height: 22,
    borderRadius: 8,
    paddingHorizontal: 4,
  },
  mockBadgeBar: {
    width: 10,
    height: 26,
    borderRadius: 3,
  },
  mockBadgeText: {
    color: colors.text,
    fontSize: 9,
    fontWeight: '900',
  },
  mockBadgeTextCompact: {
    fontSize: 8,
    lineHeight: 9,
    textAlign: 'center',
    includeFontPadding: false,
  },
  mockCol: {
    flex: 1,
    gap: 5,
    justifyContent: 'center',
  },
  mockBar: {
    height: 5,
    borderRadius: 2.5,
    backgroundColor: colors.textMuted,
    minWidth: 16,
  },
  mockTag: {
    width: 22,
    height: 14,
    borderRadius: 3,
    backgroundColor: colors.previewText,
    flexShrink: 0,
  },
  mockMiniTag: {
    height: 12,
    borderRadius: 3,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mockMiniTagText: {
    color: colors.highlight,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  mockMiniTags: {
    flexDirection: 'row',
    gap: 4,
  },
  mockText: {
    fontSize: 9,
    fontWeight: '700',
    color: colors.previewTextMuted,
    flexShrink: 1,
  },
  mockFlex: {
    flex: 1,
    justifyContent: 'center',
  },
  mockTimeText: {
    fontSize: 11,
    fontWeight: '800',
    color: colors.successText,
    flexShrink: 0,
    minWidth: 22,
    textAlign: 'right',
  },
  mockTags: {
    flexDirection: 'row',
    gap: 3,
  },
  // ── Times count row ──────────────────────────────────────────────────────────
  styleTimesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  mockPreviewNote: {
    color: colors.textTertiary,
    fontSize: 12,
    marginBottom: spacing.xs,
    textAlign: 'left',
  },
  styleTimesLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  inlineCountPicker: {
    marginTop: spacing.xs,
    gap: spacing.xs,
  },
  inlineCountLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 2,
  },
  inlineCountRow: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  inlineCountChip: {
    flex: 1,
    paddingVertical: spacing.sm,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: 'center',
  },
  inlineCountChipActive: {
    borderColor: colors.accent,
    backgroundColor: colors.surface,
  },
  inlineCountChipText: {
    color: colors.text,
    fontSize: 13,
    fontWeight: '700',
  },
  inlineCountChipTextActive: {
    color: colors.text,
  },
  inlineLabelInput: {
    minHeight: 44,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    color: colors.text,
    fontSize: 14,
    fontWeight: '500',
  },
  wizardConfirmBtn: {
    borderRadius: radii.md,
    backgroundColor: colors.accent,
    paddingVertical: spacing.md,
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  wizardConfirmBtnText: {
    color: colors.onAccent,
    fontSize: 15,
    fontWeight: '900',
  },

  // ─── Wizard Review Step ────────────────────────────────────────────────────
  wizardReviewContainer: {gap: spacing.md},
  wizardSection: {gap: spacing.xs},
  wizardSectionLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  wizardNameInput: {
    height: 50,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    color: colors.text,
    paddingHorizontal: spacing.md,
    fontSize: 17,
    fontWeight: '800',
  },

  // ─── Wizard Card (shared container) ───────────────────────────────────────
  wizardCard: {
    backgroundColor: colors.card,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  wizardCardDivider: {height: 1, backgroundColor: colors.border},
  wizardCardPadded: {padding: spacing.md, gap: spacing.xs},

  // ─── Wizard Review Rows (Your Selection) ──────────────────────────────────
  wizardReviewRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  wizardReviewRowCopy: {flex: 1, gap: 2},
  wizardReviewRowLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  wizardReviewRowValue: {color: colors.text, fontSize: 14, fontWeight: '800'},
  wizardReviewEditBtn: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexShrink: 0,
  },
  wizardReviewEditText: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},

  // ─── Wizard Field (Custom Text) ───────────────────────────────────────────
  wizardFieldLabel: {
    color: colors.textMuted,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  wizardFieldInput: {
    height: 40,
    borderRadius: radii.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    color: colors.text,
    paddingHorizontal: spacing.sm,
    fontSize: 14,
    fontWeight: '700',
    marginTop: 4,
  },

  // ─── Wizard Settings Rows ─────────────────────────────────────────────────
  wizardSettingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    gap: spacing.sm,
  },
  wizardSettingLabel: {color: colors.text, fontSize: 14, fontWeight: '700'},
  wizardStepper: {flexDirection: 'row', alignItems: 'center', gap: spacing.sm},
  wizardStepperBtn: {
    width: 30,
    height: 30,
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardStepperBtnDisabled: {opacity: 0.35},
  wizardStepperBtnText: {color: colors.text, fontSize: 16, fontWeight: '600'},
  wizardStepperValue: {color: colors.text, fontSize: 14, fontWeight: '800', minWidth: 40, textAlign: 'center'},
  wizardSegmented: {
    flexDirection: 'row',
    borderRadius: radii.sm,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    overflow: 'hidden',
  },
  wizardSegment: {paddingHorizontal: spacing.sm, paddingVertical: 6},
  wizardSegmentActive: {backgroundColor: colors.accentMuted},
  wizardSegmentText: {color: colors.textMuted, fontSize: 12, fontWeight: '700'},
  wizardSegmentTextActive: {color: colors.accent},

  // ─── Wizard Schedule ──────────────────────────────────────────────────────
  wizardScheduleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  wizardDayRow: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  wizardDayRowDisabled: {opacity: 0.35},
  wizardDayPill: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  wizardDayPillActive: {borderColor: colors.accent, backgroundColor: colors.accentMuted},
  wizardDayPillText: {color: colors.textMuted, fontSize: 9, fontWeight: '700'},
  wizardDayPillTextActive: {color: colors.accent},
  wizardTimeRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    padding: spacing.md,
  },
});
