import {colors, layout, radii, spacing, typography} from '../../../theme';

export const configSharedStyles = {
  sectionCard: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.lg,
    padding: layout.cardPadding,
    marginBottom: spacing.sm,
    gap: spacing.sm,
  },
  sectionTitle: {
    color: colors.text,
    fontSize: typography.title,
    fontWeight: '800' as const,
    marginBottom: spacing.xs,
  },
  hintText: {
    color: colors.textMuted,
    fontSize: typography.caption,
    marginBottom: spacing.xs,
  },
  stationSelector: {
    minHeight: layout.inputHeight,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    backgroundColor: colors.surface,
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
    justifyContent: 'space-between' as const,
    gap: spacing.sm,
  },
  stationSelectorOpen: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  stationSelectorPressed: {opacity: 0.9},
  stationSelectorText: {
    color: colors.text,
    fontSize: typography.label,
    fontWeight: '700' as const,
    flexShrink: 1,
  },
  stationSelectorCaret: {
    color: colors.textMuted,
    fontSize: 10,
    marginLeft: spacing.xs,
  },
  stopList: {
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.md,
    overflow: 'hidden' as const,
    marginBottom: spacing.sm,
  },
  stopListScroll: {maxHeight: 256},
  stopItem: {
    minHeight: 44,
    borderBottomColor: colors.border,
    borderBottomWidth: 1,
    backgroundColor: colors.surface,
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.sm,
    justifyContent: 'center' as const,
    gap: spacing.xxs,
  },
  stopItemSelected: {
    backgroundColor: colors.accentMuted,
    borderBottomColor: colors.accent,
  },
  stopItemPressed: {opacity: 0.85},
  stopItemTitle: {
    color: colors.text,
    fontSize: typography.label,
    fontWeight: '700' as const,
  },
  stopItemSubtitle: {
    color: colors.textMuted,
    fontSize: typography.caption,
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: typography.label,
    padding: spacing.sm,
  },
  lineGrid: {
    flexDirection: 'row' as const,
    flexWrap: 'wrap' as const,
    gap: spacing.xs,
  },
  lineChip: {
    minHeight: 40,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: radii.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    backgroundColor: colors.surface,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  lineChipActive: {
    borderColor: colors.accent,
    backgroundColor: colors.accentMuted,
  },
  lineChipText: {
    color: colors.text,
    fontSize: typography.label,
    fontWeight: '700' as const,
  },
  lineChipTextActive: {color: colors.accent},
  saveButton: {
    minHeight: layout.buttonHeight,
    marginTop: spacing.sm,
    backgroundColor: colors.accent,
    borderRadius: radii.md,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  saveButtonText: {
    color: colors.background,
    fontSize: typography.label,
    fontWeight: '800' as const,
  },
  statusNote: {
    color: colors.textMuted,
    fontSize: typography.caption,
    marginTop: spacing.sm,
  },
};
